/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.14.1/samples
 * This project uses @Incubating APIs which are subject to change.
 */
plugins {
    id("org.jetbrains.kotlin.multiplatform") version "2.1.21"
    id("org.jetbrains.kotlin.plugin.serialization") version "2.1.21"
    id("com.ben-manes.versions") version "0.46.0"
}

group = "com.trikeshed"
version = "1.0-SNAPSHOT"

kotlin {
    jvm()
    js(IR) {
        browser()
        nodejs()
        binaries.executable()
        optimize = true
    }
    wasm32("wasm") {
        binaries.executable()
        optimize = true
    }
    sourceSets {
        val commonMain by getting {
            dependencies {
                implementation(kotlin("stdlib-common"))
            }
        }
        val jsMain by getting {
            dependencies {
                implementation(npm("webpack", "5.75.0"))
                implementation(npm("webpack-cli", "5.0.1"))
            }
        }
        val wasmMain by getting
    }
}

dependencies {
    commonMainImplementation("org.jetbrains.kotlinx:kotlinx-serialization-core:1.5.0")
}

publishing {
    repositories {
        mavenLocal()
    }
    publications {
        create<MavenPublication>("mavenJs") {
            from(components["js"])
        }
        create<MavenPublication>("mavenWasm") {
            from(components["wasm"])
        }
    }
}

tasks.register("syncVersions") {
    doLast {
        val version = project.version.toString()
        file("package.json").writeText(
            file("package.json").readText()
                .replace(Regex("\"version\"\\s*:\\s*\"[^\"]+\""), "\"version\": \"$version\"")
        )
    }
}

processResources.dependsOn(syncVersions)
