// Kotlin/WASM module stub for deployment
// This would normally be generated by the Kotlin compiler

let wasmExports = {};

export default function init(input) {
    console.log('🔧 WASM module init called');
    return Promise.resolve(wasmExports);
}

export function platformMain() {
    console.log('🎮 Interactive RTS WebGPU Demo - WASM Version');
    console.log('📚 Click buttons to interact with the simulation!');
    console.log('🚀 Demo ready - using JavaScript fallback for interactive demo');
    return true;
}
