/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.14.1/userguide/multi_project_builds.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
        google()
    }
}

dependencyResolutionManagement {
    repositories {
        mavenCentral()
        google()
    }
}

rootProject.name = "superbikeshed"
include("ta4k")
include("Trikeshed")
include("nexus")
include("rtsgame")
include("moneyfan")
include("spacegraphjs:kotlin-spacegraph")
include("ta4k-spacegraph-moneyfan-demo")
include(":boingDemo")
