/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.14.1/userguide/multi_project_builds.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

rootProject.name = "superbikeshed"

// Auto-discover subprojects with build.gradle.kts files
rootDir.walkTopDown()
    .filter { it.isDirectory && it != rootDir }
    .filter { File(it, "build.gradle.kts").exists() }
    .filter { !it.absolutePath.contains("spacegraphjs/kotlin-spacegraph") } // Temporarily exclude problematic project
    .forEach { projectDir ->
        val relativePath = rootDir.toPath().relativize(projectDir.toPath())
        val projectName = relativePath.toString().replace(File.separatorChar, ':')
        include(":$projectName")
    }
