/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.14.1/userguide/multi_project_builds.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
        google()
    }
}

dependencyResolutionManagement {
    repositories {
        mavenCentral()
        google()
    }
    versionCatalogs {
        create("libs") {
            version("kotlin", "2.1.21")
            version("coroutines", "1.8.0")
            version("datetime", "0.5.0")
            version("serialization", "1.6.2")
            version("junit", "5.9.2")
        }
    }
}

rootProject.name = "Trikeshed-Monorepo"

include(":Trikeshed")
include(":brokeshed")
include(":kotlinx-serialization-scanner")
include(":kotlinx-serialization-wireproto")
include(":ta4k")
include(":nexus")
include(":rtsgame")
include(":moneyfan")
include(":spacegraph")
include(":k2script")
include(":flatton")
// include(":boingDemo")  // Temporarily disabled due to configuration issues
include(":ta4k-spacegraph-moneyfan-demo")
include(":tools")
include(":superbikeshed")
include(":museum")
include(":dgm")
include(":tests")
include(":todo")
include(":gradle")
include(":kotlin-js-store")
