plugins {
    id 'java'
}

group = 'com.example.gradle'
version = '1.0.SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.slf4j:slf4j-api:1.7.32'
    testImplementation 'junit:junit:4.13.2'
    runtimeOnly 'ch.qos.logback:logback-classic:1.2.9'

    // Map notation
    implementation group: 'com.google.guava', name: 'guava', version: '30.1-jre'

    // Platform/BOM
    implementation platform('org.springframework.boot:spring-boot-dependencies:2.7.0')
    implementation 'org.springframework.boot:spring-boot-starter-web' // Version from BOM
}
