package gk.kademlia.security

import gk.kademlia.messages.KademliaPayload
// Assuming PublicKey is defined in the same package (gk.kademlia.security) via CryptoService.kt
// If PublicKey were in its own file, a direct import might be needed, but typically it's accessible.

/**
 * A wrapper for Kademlia payloads that includes security information like
 * sender identity (via public key) and a signature.
 *
 * @param P The type of the Kademlia payload being secured.
 * @param payload The actual Kademlia message payload (e.g., PingRequest, FindNodeRequest).
 * @param senderPublicKeyEncoded The byte-encoded form of the sender's public key.
 *        This allows the recipient to decode the PublicKey for signature verification.
 * @param signature A cryptographic signature of the (typically serialized) payload,
 *        generated by the sender using their private key.
 * @param timestamp A Unix timestamp in milliseconds indicating when the message was created.
 *        Helps in preventing replay attacks.
 */
data class SecureMessage<P : KademliaPayload>(
    val payload: P,
    val senderPublicKeyEncoded: ByteArray,
    val signature: ByteArray,
    val timestamp: Long
) {
    // It's good practice to provide equals and hashCode if the data class contains ByteArray members,
    // as default implementations might rely on array identity rather than content.
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as SecureMessage<*> // Use star projection as payload type P might differ but structure is same

        if (payload != other.payload) return false
        if (!senderPublicKeyEncoded.contentEquals(other.senderPublicKeyEncoded)) return false
        if (!signature.contentEquals(other.signature)) return false
        if (timestamp != other.timestamp) return false

        return true
    }

    override fun hashCode(): Int {
        var result = payload?.hashCode() ?: 0 // Payload can be null if P is nullable, though not typical for this design
        result = 31 * result + senderPublicKeyEncoded.contentHashCode()
        result = 31 * result + signature.contentHashCode()
        result = 31 * result + timestamp.hashCode()
        return result
    }
}
