@file:Suppress("UNCHECKED_CAST", "FunctionName", "NonAsciiCharacters", "NOTHING_TO_INLINE")
package borg.trikeshed.launcher

import com.sun.jna.*
import com.sun.jna.ptr.*
import kotlinx.coroutines.*
import java.io.File
import java.net.URLClassLoader
import java.nio.file.Paths
import javax.tools.ToolProvider
import kotlin.concurrent.thread
import com.sun.jna.Native
import com.sun.jna.Platform
import kotlinx.coroutines.CompletableDeferred
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking // Already present but good to note
import java.util.concurrent.ConcurrentHashMap
import java.util.concurrent.atomic.AtomicLong

// Assuming these would be available from the superbikeshed_native library
// For now, these are placeholders for what would be generated by cinterop if IoUringOps.kt was used.
// We are defining a JNA interface here instead.
// import com.superbikeshed.trikeshed.native.uring.*
// import com.superbikeshed.trikeshed.native.*


/**
 * Platform Launcher - Dynamically loads JVM and manages WASM execution
 * 
 * This launcher can:
 * 1. Dynamically load a JVM instance in-process
 * 2. Manage WASM modules using GraalVM's Truffle framework
 * 3. Provide seamless interop between native, JVM, and WASM code
 */

// Native library interfaces
interface LibJVM : Library {
    companion object {
        val INSTANCE: LibJVM = Native.load("jvm", LibJVM::class.java)
    }
    
    fun JNI_CreateJavaVM(
        pvm: PointerByReference,
        penv: PointerByReference,
        args: JavaVMInitArgs
    ): Int
    
    fun JNI_GetCreatedJavaVMs(
        vmBuf: PointerByReference,
        bufLen: Int,
        nVMs: IntByReference
    ): Int
}

// JNI structures
class JavaVMInitArgs : Structure() {
    @JvmField var version: Int = 0
    @JvmField var nOptions: Int = 0
    @JvmField var options: Pointer? = null
    @JvmField var ignoreUnrecognized: Byte = 0
    
    override fun getFieldOrder() = listOf("version", "nOptions", "options", "ignoreUnrecognized")
}

class JavaVMOption : Structure() {
    @JvmField var optionString: String? = null
    @JvmField var extraInfo: Pointer? = null
    
    override fun getFieldOrder() = listOf("optionString", "extraInfo")
}

// Platform launcher main class
class PlatformLauncher {
    private var javaVM: Pointer? = null
    private var jniEnv: Pointer? = null
    private var wasmEngine: Any? = null
    private val loadedModules = mutableMapOf<String, WASMModule>()

    // For io_uring specific parts (JNA based)
    private var uringContext: UringContext? = null
    private val uringScope = CoroutineScope(Dispatchers.IO) // Dedicated scope for uring completions

    interface LibUringNative : Library {
        fun init_uring(entries: Int, flags: Int): Pointer? // Returns a ring_fd or context pointer
        fun exit_uring(ring_context: Pointer)
        // Returns a request ID or negative for error
        fun submit_async_read_request(
            ring_context: Pointer,
            filePath: String,
            offset: Long,
            size: Int,
            requestId: Long
        ): Int
        // Returns a request ID or negative for error
        fun submit_async_write_request(
            ring_context: Pointer,
            filePath: String,
            data: ByteArray,
            offset: Long,
            size: Int,
            requestId: Long
        ): Int

        fun get_completion(ring_context: Pointer, completionData: CompletionData, timeout_ms: Int): Int // Fills CompletionData, returns status

        companion object {
            val INSTANCE: LibUringNative? by lazy {
                if (Platform.isLinux()) {
                    try {
                        // "trikeshed_native_uring" should be the name of the compiled K/N library
                        Native.load("trikeshed_native_uring", LibUringNative::class.java) as LibUringNative
                    } catch (e: UnsatisfiedLinkError) {
                        println("Warning: Failed to load trikeshed_native_uring library for io_uring. ${e.message}")
                        null
                    }
                } else {
                    null
                }
            }
        }
    }

    // Data structure to pass to and receive from JNA get_completion
    class CompletionData : Structure() {
        @JvmField var request_id: Long = 0
        @JvmField var result: Int = 0 // e.g., bytes read/written or error code
        @JvmField var data: Pointer? = null // For read data, if applicable (or handle buffer passing differently)
        @JvmField var data_len: Int = 0

        override fun getFieldOrder(): List<String> {
            return listOf("request_id", "result", "data", "data_len")
        }

        // If data is allocated natively and needs to be freed
        fun freeData() {
            data?.let { Native.free(Pointer.nativeValue(it)) }
        }
    }
    
    private class UringContext(val nativeContext: Pointer, val lib: LibUringNative) {
        val pendingRequests = ConcurrentHashMap<Long, CompletableDeferred<Pair<Int, ByteArray?>>>()
        val nextRequestId = AtomicLong(0)
        private var completionThread: Thread? = null
        @Volatile var running = true

        fun startCompletionPolling() {
            completionThread = thread(start = true, isDaemon = true, name = "uring-completion-poller") {
                val cdata = CompletionData()
                while (running) {
                    try {
                        val ret = lib.get_completion(nativeContext, cdata, 1000) // Poll with 1s timeout
                        if (ret == 0) { // Success, completion received
                            val deferred = pendingRequests.remove(cdata.request_id)
                            if (deferred != null) {
                                if (cdata.result >= 0) {
                                    val byteArray = if (cdata.data != null && cdata.data_len > 0) {
                                        cdata.data!!.getByteArray(0, cdata.data_len)
                                    } else {
                                        null
                                    }
                                    deferred.complete(Pair(cdata.result, byteArray))
                                } else {
                                    deferred.completeExceptionally(RuntimeException("io_uring operation failed with code: ${cdata.result} for request ${cdata.request_id}"))
                                }
                            }
                            cdata.freeData() // Important if data was allocated by native side for JNA
                        } else if (ret == -1) { // Timeout, poll again
                            // Continue
                        } else { // Error during get_completion
                            println("Error in get_completion: $ret. Stopping poller.")
                            stopPolling(true, ret) // error code for ret
                            break
                        }
                    } catch (e: Exception) {
                        println("Exception in uring completion poller: ${e.message}")
                        stopPolling(true, -99) // Indicate poller exception
                        break
                    }
                }
            }
        }

        fun stopPolling(errorOccurred: Boolean = false, errorCode: Int = 0) {
            running = false
            completionThread?.interrupt() // Interrupt if it's in a blocking wait (though JNA might not be interruptible)
            try {
                completionThread?.join(2000) // Wait for thread to die
            } catch (ie: InterruptedException) {
                Thread.currentThread().interrupt()
            }
            // Clear pending requests with an error if polling is stopped unexpectedly
            if (errorOccurred || pendingRequests.isNotEmpty()) {
                 pendingRequests.forEach { (_, deferred) ->
                    if (!deferred.isCompleted) {
                         deferred.completeExceptionally(RuntimeException("io_uring context shut down or error $errorCode."))
                    }
                 }
                 pendingRequests.clear()
            }
        }
    }

    /**
     * Initialize the platform launcher
     */
    fun initialize(jvmOptions: List<String> = emptyList()) {
        // Create JVM if not already running
        if (!isJVMRunning()) {
            createJVM(jvmOptions)
        } else {
            attachToJVM()
        }
        
        // Initialize WASM engine
        initializeWASMEngine()

        // Initialize io_uring if on Linux and library is available
        LibUringNative.INSTANCE?.let { lib ->
            val nativeCtxPtr = lib.init_uring(32, 0) // 32 entries, no special flags for init
            if (nativeCtxPtr != null && nativeCtxPtr != Pointer.NULL) {
                uringContext = UringContext(nativeCtxPtr, lib)
                uringContext?.startCompletionPolling()
                println("io_uring initialized successfully.")
            } else {
                println("Warning: Failed to initialize io_uring context.")
            }
        }
    }
    
    /**
     * Check if JVM is already running in process
     */
    private fun isJVMRunning(): Boolean {
        val vmBuf = PointerByReference()
        val nVMs = IntByReference()
        
        val result = LibJVM.INSTANCE.JNI_GetCreatedJavaVMs(vmBuf, 1, nVMs)
        return result == 0 && nVMs.value > 0
    }
    
    /**
     * Create a new JVM instance
     */
    private fun createJVM(options: List<String>) {
        val args = JavaVMInitArgs()
        args.version = 0x00010008 // JNI_VERSION_1_8
        
        // Set up options
        val optionStructs = options.map { opt ->
            val option = JavaVMOption()
            option.optionString = opt
            option
        }
        
        if (optionStructs.isNotEmpty()) {
            val optionsMemory = Memory((optionStructs.size * Native.POINTER_SIZE).toLong())
            optionStructs.forEachIndexed { index, opt ->
                opt.write()
                optionsMemory.setPointer((index * Native.POINTER_SIZE).toLong(), opt.pointer)
            }
            
            args.nOptions = optionStructs.size
            args.options = optionsMemory
        }
        
        args.ignoreUnrecognized = 1
        
        val vmPtr = PointerByReference()
        val envPtr = PointerByReference()
        
        val result = LibJVM.INSTANCE.JNI_CreateJavaVM(vmPtr, envPtr, args)
        if (result != 0) {
            throw RuntimeException("Failed to create JVM: $result")
        }
        
        javaVM = vmPtr.value
        jniEnv = envPtr.value
        
        println("JVM created successfully")
    }
    
    /**
     * Attach to existing JVM
     */
    private fun attachToJVM() {
        val vmBuf = PointerByReference()
        val nVMs = IntByReference()
        
        LibJVM.INSTANCE.JNI_GetCreatedJavaVMs(vmBuf, 1, nVMs)
        javaVM = vmBuf.value
        
        // Attach current thread
        val envPtr = PointerByReference()
        // Would call AttachCurrentThread through JNI
        
        println("Attached to existing JVM")
    }
    
    /**
     * Initialize GraalVM WASM engine
     */
    private fun initializeWASMEngine() {
        try {
            // Load GraalVM classes dynamically
            val contextClass = Class.forName("org.graalvm.polyglot.Context")
            val engineClass = Class.forName("org.graalvm.polyglot.Engine")
            
            // Create engine
            val engineBuilder = engineClass.getMethod("newBuilder").invoke(null)
            val engine = engineBuilder.javaClass.getMethod("build").invoke(engineBuilder)
            
            // Create context with WASM support
            val contextBuilder = contextClass.getMethod("newBuilder", Array<String>::class.java)
                .invoke(null, arrayOf("wasm"))
            
            val context = contextBuilder.javaClass
                .getMethod("engine", engineClass)
                .invoke(contextBuilder, engine)
                .let { it.javaClass.getMethod("build").invoke(it) }
            
            wasmEngine = context
            println("WASM engine initialized")
            
        } catch (e: Exception) {
            println("Failed to initialize WASM engine: ${e.message}")
            // Fallback to custom WASM implementation
            wasmEngine = SimpleWASMEngine()
        }
    }
    
    /**
     * Load and execute a WASM module
     */
    suspend fun loadWASMModule(
        name: String,
        wasmPath: String,
        imports: Map<String, Any> = emptyMap()
    ): WASMModule = coroutineScope {
        
        val module = WASMModule(name, wasmPath)
        
        try {
            if (wasmEngine != null && wasmEngine!!.javaClass.name.contains("graalvm")) {
                // Use GraalVM WASM
                loadWithGraalVM(module, imports)
            } else {
                // Use custom implementation
                loadWithCustomEngine(module, imports)
            }
            
            loadedModules[name] = module
            println("Loaded WASM module: $name")
            
        } catch (e: Exception) {
            println("Failed to load WASM module $name: ${e.message}")
            throw e
        }
        
        module
    }
    
    /**
     * Load module using GraalVM
     */
    private fun loadWithGraalVM(module: WASMModule, imports: Map<String, Any>) {
        val context = wasmEngine!!
        
        // Read WASM file
        val wasmBytes = File(module.path).readBytes()
        
        // Create source
        val sourceClass = Class.forName("org.graalvm.polyglot.Source")
        val source = sourceClass.getMethod(
            "newBuilder",
            String::class.java,
            ByteArray::class.java,
            String::class.java
        ).invoke(null, "wasm", wasmBytes, module.name)
            .let { it.javaClass.getMethod("build").invoke(it) }
        
        // Evaluate source
        val value = context.javaClass.getMethod("eval", sourceClass).invoke(context, source)
        
        // Store instance
        module.instance = value
        
        // Set up imports
        imports.forEach { (name, impl) ->
            // Would bind imports to WASM module
        }
    }
    
    /**
     * Load module using custom engine
     */
    private fun loadWithCustomEngine(module: WASMModule, imports: Map<String, Any>) {
        val engine = wasmEngine as SimpleWASMEngine
        module.instance = engine.loadModule(module.path, imports)
    }
    
    /**
     * Execute a function in a WASM module
     */
    suspend fun executeWASMFunction(
        moduleName: String,
        functionName: String,
        vararg args: Any
    ): Any? = coroutineScope {
        
        val module = loadedModules[moduleName]
            ?: throw IllegalArgumentException("Module not loaded: $moduleName")
        
        withContext(Dispatchers.IO) {
            if (module.instance != null && module.instance!!.javaClass.name.contains("graalvm")) {
                // GraalVM execution
                executeWithGraalVM(module.instance!!, functionName, *args)
            } else {
                // Custom execution
                executeWithCustomEngine(module.instance!!, functionName, *args)
            }
        }
    }
    
    private fun executeWithGraalVM(instance: Any, functionName: String, vararg args: Any): Any? {
        val member = instance.javaClass.getMethod("getMember", String::class.java)
            .invoke(instance, functionName)
        
        return member?.javaClass?.getMethod("execute", Array<Any>::class.java)
            ?.invoke(member, args)
    }
    
    private fun executeWithCustomEngine(instance: Any, functionName: String, vararg args: Any): Any? {
        return (instance as SimpleWASMEngine.Module).execute(functionName, *args)
    }
    
    /**
     * Compile Java code dynamically
     */
    fun compileAndLoadJava(
        className: String,
        sourceCode: String,
        classPath: List<String> = emptyList()
    ): Class<*> {
        val compiler = ToolProvider.getSystemJavaCompiler()
            ?: throw RuntimeException("No Java compiler available")
        
        val tempDir = File(System.getProperty("java.io.tmpdir"), "platform-launcher-${System.nanoTime()}")
        tempDir.mkdirs()
        
        try {
            // Write source file
            val sourceFile = File(tempDir, "$className.java")
            sourceFile.writeText(sourceCode)
            
            // Compile
            val fileManager = compiler.getStandardFileManager(null, null, null)
            val compilationUnits = fileManager.getJavaFileObjects(sourceFile)
            
            val task = compiler.getTask(
                null,
                fileManager,
                null,
                listOf("-d", tempDir.absolutePath) + classPath.map { "-cp $it" },
                null,
                compilationUnits
            )
            
            if (!task.call()) {
                throw RuntimeException("Compilation failed")
            }
            
            // Load compiled class
            val classLoader = URLClassLoader(arrayOf(tempDir.toURI().toURL()))
            return classLoader.loadClass(className)
            
        } finally {
            // Cleanup
            tempDir.deleteRecursively()
        }
    }
    
    /**
     * Create a bridge between JVM and WASM
     */
    fun createJVMWASMBridge(
        wasmModule: String,
        javaInterface: Class<*>
    ): Any {
        return java.lang.reflect.Proxy.newProxyInstance(
            javaInterface.classLoader,
            arrayOf(javaInterface)
        ) { _, method, args ->
            runBlocking {
                executeWASMFunction(wasmModule, method.name, *(args ?: emptyArray()))
            }
        }
    }
    
    /**
     * Shutdown the platform
     */
    fun shutdown() {
        // Unload WASM modules
        loadedModules.clear()
        
        // Close WASM engine
        wasmEngine?.let {
            if (it.javaClass.name.contains("graalvm")) {
                try {
                    it.javaClass.getMethod("close").invoke(it)
                    println("GraalVM WASM context closed.")
                } catch (e: Exception) {
                    println("Error closing GraalVM WASM context: ${e.message}")
                }
            }
        }
        wasmEngine = null // Release reference
        
        // Detach from JVM (but don't destroy it)
        // Would call DetachCurrentThread through JNI
        
        // Shutdown io_uring context
        uringContext?.let { ctx ->
            ctx.stopPolling()
            ctx.lib.exit_uring(ctx.nativeContext)
            println("io_uring context shut down.")
        }
        uringContext = null

        println("Platform launcher shutdown")
    }

    // Public API for io_uring async file read
    suspend fun asyncReadFileUring(filePath: String, offset: Long = 0, size: Int = -1): ByteArray {
        val context = uringContext ?: throw IllegalStateException("io_uring not available or not initialized.")

        // For simplicity, if size is -1, we'd ideally stat the file to get its size.
        // This would require another uring op (statx) or a blocking stat.
        // For now, user must provide a reasonable size or we read a fixed chunk.
        val readSize = if (size <= 0) 4096 else size // Default to 4KB if no size

        val requestId = context.nextRequestId.incrementAndGet()
        val deferred = CompletableDeferred<Pair<Int, ByteArray?>>()
        context.pendingRequests[requestId] = deferred

        val ret = context.lib.submit_async_read_request(context.nativeContext, filePath, offset, readSize, requestId)
        if (ret < 0) {
            context.pendingRequests.remove(requestId)
            throw RuntimeException("Failed to submit async read request for $filePath, error: $ret")
        }

        val (bytesRead, data) = deferred.await()
        if (bytesRead < 0) {
            throw RuntimeException("Async read operation failed for $filePath, result: $bytesRead")
        }
        return data ?: byteArrayOf() // Should contain data if bytesRead > 0
    }

    // Public API for io_uring async file write
    suspend fun asyncWriteFileUring(filePath: String, data: ByteArray, offset: Long = 0): Int {
        val context = uringContext ?: throw IllegalStateException("io_uring not available or not initialized.")

        val requestId = context.nextRequestId.incrementAndGet()
        val deferred = CompletableDeferred<Pair<Int, ByteArray?>>() // ByteArray? is not used for write result
        context.pendingRequests[requestId] = deferred

        val ret = context.lib.submit_async_write_request(context.nativeContext, filePath, data, offset, data.size, requestId)
        if (ret < 0) {
            context.pendingRequests.remove(requestId)
            throw RuntimeException("Failed to submit async write request for $filePath, error: $ret")
        }

        val (bytesWritten, _) = deferred.await()
        if (bytesWritten < 0) {
            throw RuntimeException("Async write operation failed for $filePath, result: $bytesWritten")
        }
        return bytesWritten
    }
}

// WASM module representation
data class WASMModule(
    val name: String,
    val path: String,
    var instance: Any? = null
)

// Simple WASM engine implementation (fallback)
class SimpleWASMEngine {
    init {
        println("ERROR: SimpleWASMEngine fallback is active. GraalVM WASM engine failed to initialize. WASM execution will not be functional.")
    }

    fun loadModule(path: String, imports: Map<String, Any>): Module {
        println("ERROR: Attempted to load WASM module '$path' using SimpleWASMEngine. This engine is non-functional.")
        throw UnsupportedOperationException("SimpleWASMEngine is a non-functional fallback. GraalVM is required for WASM execution.")
    }
    
    // Module class remains but its methods will effectively be unusable if loadModule throws.
    class Module(
        private val path: String,
        private val imports: Map<String, Any>
    ) {
        fun execute(functionName: String, vararg args: Any): Any? {
            println("ERROR: Attempted to execute function '$functionName' in WASM module '$path' using SimpleWASMEngine. This engine is non-functional.")
            throw UnsupportedOperationException("SimpleWASMEngine is a non-functional fallback. GraalVM is required for WASM execution.")
        }
    }
}

// Platform launcher entry point
fun main(args: Array<String>) = runBlocking {
    val launcher = PlatformLauncher()
    
    // Initialize with custom JVM options
    launcher.initialize(listOf(
        "-Xmx2g",
        "-XX:+UseG1GC",
        "-Dpolyglot.engine.WarnInterpreterOnly=false"
    ))
    
    // Example: Load a WASM module
    launcher.loadWASMModule(
        name = "example",
        wasmPath = "example.wasm",
        imports = mapOf(
            "console" to object {
                fun log(msg: String) = println("WASM: $msg")
            }
        )
    )
    
    // Example: Compile and load Java dynamically
    val dynamicClass = launcher.compileAndLoadJava(
        className = "DynamicExample",
        sourceCode = """
            public class DynamicExample {
                public static String greet(String name) {
                    return "Hello, " + name + " from dynamic Java!";
                }
            }
        """.trimIndent()
    )
    
    val result = dynamicClass.getMethod("greet", String::class.java)
        .invoke(null, "World")
    println(result)
    
    // Example: Execute WASM function
    launcher.executeWASMFunction("example", "main")
    
    // Create bridge
    interface ExampleService {
        fun calculate(a: Int, b: Int): Int
    }
    
    val bridge = launcher.createJVMWASMBridge("example", ExampleService::class.java) as ExampleService
    
    // Shutdown
    launcher.shutdown()
}