[versions]
gradle =  "8.14.2"
benmanes = "0.51.0"
kotlin = { strictly = "[1.0, 2.2[", prefer = "2.1.21" }
coroutines = { strictly = "[1.0, 2.2[", prefer = "1.10.2" }
serialization = { strictly = "[1.0, 2.2[", prefer = "1.7.3" }
datetime = { strictly = "[0.4, 2.0[", prefer = "0.6.2" }
scripting-dependencies = { strictly = "[1.0, 2.2[", prefer = "2.1.21" }
scripting-dependencies-maven = { strictly = "[1.0, 2.2[", prefer = "2.1.21" }

[libraries]
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-scripting-jvm = { module = "org.jetbrains.kotlin:kotlin-scripting-jvm", version.ref = "kotlin" }
kotlin-scripting-jvm-host = { module = "org.jetbrains.kotlin:kotlin-scripting-jvm-host", version.ref = "kotlin" }
kotlin-scripting-dependencies = { module = "org.jetbrains.kotlin:kotlin-scripting-dependencies", version.ref = "scripting-dependencies" }
kotlin-scripting-dependencies-maven = { module = "org.jetbrains.kotlin:kotlin-scripting-dependencies-maven", version.ref = "scripting-dependencies-maven" }
coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "datetime" }

[plugins]
benmanes-versions = { id = "com.github.ben-manes.versions", version.ref = "benmanes" } 