package com.ta4k.strategy.examples

import com.ta4k.core.model.Kline
import com.ta4k.indicators.SMAIndicator
import com.ta4k.strategy.Strategy
import com.ta4k.trading.entities.Order
import com.ta4k.trading.entities.OrderType
import com.ta4k.trading.entities.Position
import java.math.BigDecimal

/**
 * A simple trading strategy based on the crossover of two Simple Moving Averages (SMAs).
 *
 * @property klineSeries The kline series on which this strategy operates.
 * @property shortSmaPeriod The period for the shorter SMA.
 * @property longSmaPeriod The period for the longer SMA.
 * @property defaultOrderAmount The default amount for orders generated by this strategy.
 */
class SMACrossoverStrategy(
    override val klineSeries: Indexed<Kline>,
    private val shortSmaPeriod: Int,
    private val longSmaPeriod: Int,
    private val defaultOrderAmount: BigDecimal = BigDecimal("1.0") // Default amount to trade
) : Strategy {

    init {
        require(shortSmaPeriod > 0) { "Short SMA period must be positive." }
        require(longSmaPeriod > 0) { "Long SMA period must be positive." }
        require(shortSmaPeriod < longSmaPeriod) { "Short SMA period must be less than long SMA period." }
    }

    private val shortSma: SMAIndicator = SMAIndicator(klineSeries, shortSmaPeriod)
    private val longSma: SMAIndicator = SMAIndicator(klineSeries, longSmaPeriod)

    /**
     * The warm-up period required for the indicators used in this strategy.
     * This is determined by the longest period of the indicators used (long SMA).
     */
    override val warmUpPeriod: Int = longSmaPeriod

    /**
     * Generates a trading signal based on SMA crossovers.
     *
     * @param index The current kline index.
     * @param currentPosition The currently open position, or null if no position is open.
     * @return An [Order] if a signal is generated, otherwise null.
     */
    override fun generateSignal(index: Int, currentPosition: Position?): Order? {
        // Ensure index is valid and indicators are warmed up.
        // Warm-up check is technically handled by backtester using warmUpPeriod,
        // but an additional check here for direct calls or safety is fine.
        if (index < this.warmUpPeriod) {
            return null
        }
        // Need at least index 1 to compare with index - 1 for crossover detection.
        // Also, SMA values might only be available from warmUpPeriod onwards.
        // SMAIndicator.getValue(idx) returns null if idx < period-1.
        // So, for SMA(longSmaPeriod), getValue(longSmaPeriod-1) is the first non-null.
        // To check crossover at 'index', we need SMA values at 'index' and 'index-1'.
        // So, 'index-1' must be >= longSmaPeriod-1, meaning 'index' must be >= longSmaPeriod.
        // This is consistent with warmUpPeriod.
        if (index == 0) return null // Cannot get index - 1 if index is 0.

        val shortSmaPrev = shortSma.getValue(index - 1)
        val longSmaPrev = longSma.getValue(index - 1)
        val shortSmaCurr = shortSma.getValue(index)
        val longSmaCurr = longSma.getValue(index)

        if (shortSmaPrev == null || longSmaPrev == null || shortSmaCurr == null || longSmaCurr == null) {
            // This condition means SMAs are not yet fully calculated, which should align with warmUpPeriod logic.
            return null
        }

        val currentPrice = klineSeries[index].closePrice // For order price reference

        if (currentPosition == null) { // No open position, look for entry
            // Golden Cross: Short SMA crosses above Long SMA
            if (shortSmaPrev < longSmaPrev && shortSmaCurr > longSmaCurr) {
                return Order(
                    klineIndex = index,
                    type = OrderType.BUY,
                    price = currentPrice, // Signal generated at this price point
                    amount = defaultOrderAmount
                )
            }
        } else { // Open position exists, look for exit
            // Death Cross: Short SMA crosses below Long SMA (as an exit signal for a BUY position)
            if (currentPosition.type == OrderType.BUY && shortSmaPrev > longSmaPrev && shortSmaCurr < longSmaCurr) {
                return Order(
                    klineIndex = index,
                    type = OrderType.SELL, // Signal to sell (close the long position)
                    price = currentPrice,
                    amount = currentPosition.amount // Close the full position amount
                )
            }
            // Note: This strategy does not implement short selling entries or exits from short positions.
            // It's a simple long-only crossover strategy.
        }
        return null // No signal
    }
}
