// js/core/commands.js

/**
 * Defines the types and structures for game commands (actions) used in the Redux-like state management pattern.
 * These commands are intended to be the sole way to propose changes to the game state.
 * Reducers will process these commands to produce new state.
 */

export const GameCommandTypes = {
    // Game Lifecycle
    INITIALIZE_GAME: 'INITIALIZE_GAME', // Payload: { config } (initial seed, map settings, etc.)
    START_GAME: 'START_GAME',           // Payload: null
    PAUSE_GAME: 'PAUSE_GAME',           // Payload: null
    RESUME_GAME: 'RESUME_GAME',         // Payload: null
    END_GAME: 'END_GAME',               // Payload: { winner, reason }

    // Game State Updates
    ADVANCE_GAME_TIME: 'ADVANCE_GAME_TIME', // Payload: { deltaTime }
    UPDATE_RESOURCES: 'UPDATE_RESOURCES',   // Payload: { team, deltas: { mass, energy } }
    SET_PAUSED: 'SET_PAUSED',             // Payload: { isPaused: boolean }
    DECLARE_WINNER: 'DECLARE_WINNER',       // Payload: { winningTeam: string | null }
    ADD_EVENT: 'ADD_EVENT',               // Payload: { eventData: object }
    // ADD_EVENT_INTERNAL can be removed if ADD_EVENT is used by GameState.addEvent internally
    
    // Entity Manipulation
    TELEPORT_UNIT: 'TELEPORT_UNIT',       // Payload: { unitId, targetPosition: {x, y} }

    // Entity Creation
    CREATE_UNIT: 'CREATE_UNIT',         // Payload: { unitId (optional, could be generated), type, team, position }
    CREATE_BUILDING: 'CREATE_BUILDING', // Payload: { buildingId (optional), type, team, position }
    CREATE_PROJECTILE: 'CREATE_PROJECTILE', // Payload: { projectileData } (type, owner, target, etc.)
    CREATE_EFFECT: 'CREATE_EFFECT',       // Payload: { effectData } (type, position, duration, etc.)
    CREATE_CAPTION: 'CREATE_CAPTION',     // Payload: { captionData }

    // Entity State Changes (Examples - more granular commands are better)
    // Instead of a generic UPDATE_UNIT, specific commands are preferred:
    MOVE_UNIT: 'MOVE_UNIT',                     // Payload: { unitId, path (or targetPosition) }
    UNIT_ATTACK_TARGET: 'UNIT_ATTACK_TARGET',   // Payload: { unitId, targetId }
    UNIT_TAKE_DAMAGE: 'UNIT_TAKE_DAMAGE',       // Payload: { unitId, damageAmount, damageType, sourceId }
    UNIT_START_CONSTRUCTION: 'UNIT_START_CONSTRUCTION', // Payload: { unitId (ACU/Eng), buildingType, position }
    UNIT_CONSTRUCTION_PROGRESS: 'UNIT_CONSTRUCTION_PROGRESS', // Payload: { unitId, deltaTime }
    
    BUILDING_PRODUCTION_QUEUE_ADD: 'BUILDING_PRODUCTION_QUEUE_ADD', // Payload: { buildingId, unitType }
    BUILDING_PRODUCTION_PROGRESS: 'BUILDING_PRODUCTION_PROGRESS',// Payload: { buildingId, deltaTime }
    
    DESTROY_ENTITY: 'DESTROY_ENTITY',           // Payload: { entityId, entityType (unit/building) }

    // AI Commands (examples of what AI might dispatch)
    AI_COMMAND_GROUP_MOVE: 'AI_COMMAND_GROUP_MOVE', // Payload: { groupIds, targetPosition, formation }
    AI_COMMAND_UNIT_ACTION: 'AI_COMMAND_UNIT_ACTION', // Payload: { unitId, actionType, targetId, targetPosition }

    // Input from Player (these would be generated by input handlers)
    PLAYER_COMMAND_SELECT_UNIT: 'PLAYER_COMMAND_SELECT_UNIT',     // Payload: { unitId: string, isMultiSelect: boolean }
    PLAYER_COMMAND_DESELECT_ALL: 'PLAYER_COMMAND_DESELECT_ALL',   // Payload: {}
    PLAYER_COMMAND_MOVE_UNITS: 'PLAYER_COMMAND_MOVE_UNITS',       // Payload: { unitIds: string[], targetPosition: {x, y} }
    PLAYER_COMMAND_UNIT_ATTACK: 'PLAYER_COMMAND_UNIT_ATTACK',     // Payload: { selectedUnitIds, targetEntityId }
    PLAYER_COMMAND_BUILD_STRUCTURE: 'PLAYER_COMMAND_BUILD_STRUCTURE',// Payload: { builderUnitId, structureType, position }
    PLAYER_COMMAND_QUEUE_PRODUCTION: 'PLAYER_COMMAND_QUEUE_PRODUCTION', // Payload: { factoryId, unitTypeToProduce }

    // Deterministic RNG State (if managed via commands, less likely, usually part of context)
    // ADVANCE_RNG: 'ADVANCE_RNG', // Payload: { count } or implicitly handled by reducers using RNG.
};

/**
 * Action creator examples (optional, but good practice)
 * 
 * export function createUnit(unitId, type, team, position) {
 *   return { type: GameCommandTypes.CREATE_UNIT, payload: { unitId, type, team, position } };
 * }
 * 
 * export function moveUnit(unitId, targetPosition) {
 *   return { type: GameCommandTypes.MOVE_UNIT, payload: { unitId, targetPosition } };
 * }
 */

// This file primarily defines the command types and their expected payload structures.
// Actual action creator functions can be added here or in separate files if preferred.
// The reducers will use these types to process commands.
