package borg.ksp.processors

import com.google.devtools.ksp.processing.*
import com.google.devtools.ksp.symbol.*
import com.google.devtools.ksp.validate
import java.io.OutputStreamWriter

class LoopOptimizerProcessor(
    private val codeGenerator: CodeGenerator,
    private val logger: KSPLogger
) : SymbolProcessor {

    override fun process(resolver: Resolver): List<KSAnnotated> {
        val annotationName = "borg.entityscanner.annotations.OptimizeLoop"
        val symbols = resolver.getSymbolsWithAnnotation(annotationName).filterIsInstance<KSClassDeclaration>()

        if (!symbols.iterator().hasNext()) {
            return emptyList()
        }

        val validSymbols = symbols.filter { it.validate() }

        validSymbols.forEach { ksClass ->
            if (ksClass.classKind == ClassKind.ENUM_CLASS) {
                generateOptimizedLoop(ksClass)
            } else {
                logger.error("@OptimizeLoop can only be applied to enum classes.", ksClass)
            }
        }

        return symbols.filterNot { it.validate() }.toList()
    }

    private fun generateOptimizedLoop(ksClass: KSClassDeclaration) {
        val packageName = ksClass.packageName.asString()
        val className = ksClass.simpleName.asString()
        val enumEntries = ksClass.declarations.filterIsInstance<KSClassDeclaration>()
            .filter { it.classKind == ClassKind.ENUM_ENTRY }.toList()
        val size = enumEntries.size

        if (size == 0) {
            logger.warn("Skipping @OptimizeLoop for empty enum $className.", ksClass)
            return
        }

        val counterType = when {
            size <= Byte.MAX_VALUE -> "Byte"
            size <= Short.MAX_VALUE -> "Short"
            else -> "Int" // Fallback for larger enums
        }
        
        val generatedCode = """
package $packageName

/**
 * Generated by KSP LoopOptimizerProcessor.
 * Provides a loop with an optimized counter type ($counterType).
 */
inline fun ${className}.Companion.forEachOptimized(action: ($className) -> Unit) {
    val values = $className.entries
    var i: $counterType = 0
    while (i < values.size) {
        action(values[i.toInt()])
        i++
    }
}
""".trimIndent()

        try {
            val file = codeGenerator.createNewFile(
                dependencies = Dependencies(true, ksClass.containingFile!!),
                packageName = packageName,
                fileName = "${className}LoopOptimizer"
            )
            OutputStreamWriter(file).use { writer ->
                writer.write(generatedCode)
            }
        } catch (e: Exception) {
            logger.error("Error generating optimized loop for $className: ${e.message}", ksClass)
        }
    }
}

class LoopOptimizerProcessorProvider : SymbolProcessorProvider {
    override fun create(environment: SymbolProcessorEnvironment): SymbolProcessor {
        return LoopOptimizerProcessor(environment.codeGenerator, environment.logger)
    }
} 