// Bao-Cline/src/kotlinBridge.ts

// The module name 'Bao-Cline-Kotlin' comes from settings.gradle.kts (rootProject.name)
// The actual path is derived from the wasmJsBrowserProductionWebpack task configuration in build.gradle.kts:
// destinationDirectory = project.layout.buildDirectory.dir("produção/kotlin-js-min")
// outputFileName = "wasm/Bao-Cline-Kotlin.js"
// So, the path relative to the project root would be 'Bao-Cline/build/produção/kotlin-js-min/wasm/Bao-Cline-Kotlin.js'
// If kotlinBridge.ts is in 'Bao-Cline/src/', the relative path would be:
// '../build/produção/kotlin-js-min/wasm/Bao-Cline-Kotlin.js'

let ktExports: any = null;

async function loadKotlinModule() {
    if (ktExports) return ktExports;

    try {
        // Adjust the import path based on the Gradle output.
        // Assuming this kotlinBridge.ts file is in Bao-Cline/src/
        // The path needs to correctly point to the JS file generated by webpack for the WASM module.
        const module = await import(/* webpackIgnore: true */ '../build/produção/kotlin-js-min/wasm/Bao-Cline-Kotlin.js');

        // The Kotlin compiler for WASM exports functions at the top level of the generated JS module by default,
        // especially when using @file:JsExport or @JsExport on functions/classes in the root package.
        // If you have a package structure in Kotlin (e.g., package com.example.logic),
        // then it might be module.com.example.logic.processUserRequest
        // For now, assuming root package or that webpack/Kotlin plugin handles namespacing predictably.
        ktExports = module;

        if (!ktExports.processUserRequest || !ktExports.addTaskEvent) {
            console.warn("Loaded Kotlin module:", ktExports);
            throw new Error("One or more expected Kotlin functions (processUserRequest, addTaskEvent) not found on the loaded module. Check module structure and export configuration.");
        }
        return ktExports;
    } catch (e) {
        console.error("Error loading Kotlin WASM module:", e);
        // Fallback or rethrow, depending on desired error handling
        throw new Error(`Failed to load Kotlin WASM module. Path: ../build/produção/kotlin-js-min/wasm/Bao-Cline-Kotlin.js. Error: ${e}`);
    }
}

// Define interfaces for the Kotlin data classes if they are not directly imported
// These should match the structure of the @JsExport-ed Kotlin classes.
// TypeScript cannot directly use Kotlin type aliases like KotlinExtensionState = Join<ActiveSession, EnvironmentContext>.
// We need to define the shape of KotlinExtensionState as it would appear in JS.

export interface UserRequest {
    text: string;
}

export interface Response {
    text: string;
}

export interface TaskEvent {
    ts: number; // Kotlin Long becomes number in JS
    type: string;
    ask?: string; // Corresponds to ClineAskType enum
    say?: string; // Corresponds to ClineSayType enum
    text?: string;
    images?: string[];
    partial?: boolean;
    reasoning?: string;
    conversationHistoryIndex?: number;
    checkpoint?: Record<string, string>;
    progressStatus?: { icon?: string; text?: string }; // ToolProgressStatus
    contextCondense?: { cost: number; prevContextTokens: number; newContextTokens: number; summary: string }; // ContextCondense
    tokenUsage?: { totalTokensIn: number; totalTokensOut: number; totalCacheWrites?: number; totalCacheReads?: number; totalCost: number; contextTokens: number }; // TokenUsage
}

// Simplified Series structure for JS representation
export interface Series<T> {
    items: T[];
}

export type TaskHistory = Series<TaskEvent>;

// Simplified ActiveSession structure for JS
export interface ActiveSession {
    currentTaskId?: string;
    currentMode?: any; // ModeConfig - define if needed, using 'any' for now
    history?: TaskHistory;
}

// Simplified EnvironmentContext structure for JS
export interface EnvironmentContext {
    workspaceRoot?: string;
    openFiles?: string[];
    vscodeVersion?: string;
    extensionVersion?: string;
    userPreferences?: { preferredLanguage?: string; theme?: string; allowTelemetry?: boolean }; // UserPreferences
}

// Structure for Join<A, B>
export interface Join<A, B> {
    first: A;
    second: B;
}

// Define KotlinExtensionState based on Join<ActiveSession, EnvironmentContext>
export type KotlinExtensionState = Join<ActiveSession, EnvironmentContext>;


export async function processUserRequest_bridge(state: KotlinExtensionState, request: UserRequest): Promise<Join<Response, KotlinExtensionState>> {
    const m = await loadKotlinModule();
    if (m && m.processUserRequest) {
        // Assuming processUserRequest is exported as a top-level function from the Kotlin module.
        // If it's an extension function, it might be namespaced or require the receiver as the first argument.
        // For `fun KotlinExtensionState.processUserRequest(...)`, the JS/WASM compiler typically makes it:
        // `processUserRequest(receiver: KotlinExtensionState, request: UserRequest)`
        return m.processUserRequest(state, request);
    } else {
        console.error("Loaded module for processUserRequest:", m);
        throw new Error("Kotlin function 'processUserRequest' not found on module.");
    }
}

export async function addTaskEvent_bridge(history: TaskHistory, event: TaskEvent): Promise<TaskHistory> {
    const m = await loadKotlinModule();
    if (m && m.addTaskEvent) {
        return m.addTaskEvent(history, event);
    } else {
        console.error("Loaded module for addTaskEvent:", m);
        throw new Error("Kotlin function 'addTaskEvent' not found on module.");
    }
}

// Example of how to potentially initialize and use:
/*
async function exampleUsage() {
    try {
        const initialState: KotlinExtensionState = {
            first: { // ActiveSession
                currentTaskId: "task-1",
                history: { items: [] }
            },
            second: { // EnvironmentContext
                workspaceRoot: "/path/to/workspace"
            }
        };
        const userRequest: UserRequest = { text: "Hello Kotlin WASM" };

        const result = await processUserRequest_bridge(initialState, userRequest);
        console.log("Response from Kotlin:", result.first.text);
        console.log("New state:", result.second);

        const newEvent: TaskEvent = { ts: Date.now(), type: "say", text: "Another event" };
        const updatedHistory = await addTaskEvent_bridge(result.second.first.history!, newEvent);
        console.log("Updated history:", updatedHistory);

    } catch (error) {
        console.error("Error during example usage:", error);
    }
}

// exampleUsage();
*/
