import kotlin.math.*
package rtsgame // Or rtsgame.backlog, or rtsgame.future
import kotlinx.datetime.*
import kotlin.time.*

// Note: This file serves as a backlog and gap analysis, capturing concepts
// from older 'rtsgame/museum/' projects that could enhance the current KMP rtsgame.
// These definitions are starting points for future development.

// --- I. Core Entity Component System (ECS) Abstractions ---

/**
 * Represents a unique entity in the game world.
 * In a full ECS, this might just be an ID, with components holding all data.
 * Origin: General ECS pattern, inspired by component structures in 'retired/' and 'rtsgame-kmp/'.
 */
typealias EntityId = String // Or value class EntityId(val id: String)

/**
 * Base interface for all components that can be attached to an entity.
 * Components should primarily be data containers.
 * Origin: General ECS pattern.
 */
interface Component

/**
 * Manages entities and their components.
 * Origin: General ECS pattern.
 */
interface EntityManager {
    fun createEntity(vararg components: Component): EntityId
    fun destroyEntity(entityId: EntityId)
    fun addComponent(entityId: EntityId, component: Component)
    fun <T : Component> removeComponent(entityId: EntityId, componentType: kotlin.reflect.KClass<T>)
    fun <T : Component> getComponent(entityId: EntityId, componentType: kotlin.reflect.KClass<T>): T?
    fun getAllEntitiesWithComponent(componentType: kotlin.reflect.KClass<out Component>): List<EntityId>
    // Consider: fun <T1: Component, T2: Component> getAllEntitiesWithComponents(c1Type: KClass<T1>, c2Type: KClass<T2>): List<EntityId>
}

/**
 * Base interface for game systems that operate on entities with specific components.
 * Systems contain the logic that transforms component data.
 * Origin: General ECS pattern, 'retired/core/systems/', 'rtsgame-kmp/shared/systems/'.
 */
interface GameSystem {
    /**
     * Called every game tick to update the system's state and entities.
     * @param gameState The current, possibly read-only, game state.
     * @param entityManager For querying/modifying entities and components.
     * @param deltaTime Time elapsed since the last tick.
     * @return Potentially a list of events or commands generated by the system.
     */
    fun update(entityManager: EntityManager, deltaTime: Float /*, eventBus: EventBus? */)
    // Consider adding: fun initialize(entityManager: EntityManager, eventBus: EventBus?)
}

// --- II. Essential Components ---

data class PositionComponent(var x: Float, var y: Float, var z: Float = 0f) : Component {
    // Could add helper methods for distance, angle, etc.
    // Origin: 'retired/core/components/positionComponent.ts', 'rtsgame-kmp/shared/map/Position.kt'.
}

data class VelocityComponent(var vx: Float, var vy: Float, var vz: Float = 0f) : Component {
    // Origin: Implied by movement logic in museum projects.
}

data class HealthComponent(
    var currentHp: Float,
    var maxHp: Float,
    var lastAttacker: EntityId? = null
    // Consider: resistances, regenerationDelay, etc.
) : Component {
    // Origin: 'retired/core/components/healthComponent.ts'.
    fun isAlive(): Boolean = currentHp > 0
}

data class OwnerComponent(val teamId: Int, val playerId: String? = null) : Component {
    // Identifies which team/player an entity belongs to.
    // Origin: 'team' property in museum entities.
}

data class EntityTypeComponent(val type: UnitTypeDefinition) : Component {
    // Links an entity to its static definition (stats, abilities).
    // Origin: 'type' property in 'retired/unit.ts', 'UnitType' enum in 'rtsgame-kmp'.
}

// --- III. Gameplay Systems Interfaces (examples) ---

interface CommandSystem : GameSystem {
    // Responsible for receiving and dispatching commands to entities.
    // Origin: 'retired/core/command/', 'rtsgame-kmp/shared/command/Command.kt'.
    fun issueCommand(command: Command)
}

interface MovementSystem : GameSystem {
    // Handles entity movement, pathfinding, and collision avoidance.
    // Origin: 'retired/core/systems/movementSystem.ts', 'rtsgame-kmp/shared/systems/MovementSystem.kt'.
}

interface CombatSystem : GameSystem {
    // Manages combat interactions, damage calculation, projectiles.
    // Origin: 'retired/core/systems/combatSystem.ts', 'rtsgame-kmp/shared/systems/CombatSystem.kt'.
}

interface ResourceSystem : GameSystem {
    // Manages resource generation, storage, and player resource states.
    // Origin: 'retired/core/resourceManager.ts', 'rtsgame-kmp/shared/systems/ResourceSystem.kt'.
}

interface AISystem : GameSystem {
    // Controls behavior of AI-controlled entities.
    // Origin: 'retired/ai/strategicAI.ts'.
}

interface ProductionSystem : GameSystem {
    // Handles unit/building creation queues and processes.
    // Origin: 'BuildCommand' / 'TrainUnitCommand' in 'rtsgame-kmp', construction logic in 'retired/unit.ts'.
}

// --- IV. Command Structure ---

/**
 * Base interface for all game commands.
 * Origin: 'rtsgame-kmp/shared/command/Command.kt'.
 */
sealed interface Command {
    val issuerEntityId: EntityId? // Entity that issued the command, if applicable
}

data class MoveCommand(
    val targetEntityIds: List<EntityId>,
    val destination: PositionComponent, // Using PositionComponent for consistency
    override val issuerEntityId: EntityId? = null
) : Command

data class AttackCommand(
    val attackerEntityIds: List<EntityId>,
    val targetEntityId: EntityId,
    override val issuerEntityId: EntityId? = null
) : Command

data class PatrolCommand(
    val targetEntityIds: List<EntityId>,
    val waypoints: List<PositionComponent>,
    override val issuerEntityId: EntityId? = null
) : Command

// Add other commands: BuildCommand, GatherCommand, AbilityActivationCommand, etc.

// --- V. Entity Definition and Configuration ---

/**
 * Static definition for a type of unit or building.
 * Contains base stats, abilities, model info, etc.
 * Origin: 'retired/config/unitTypes.ts', 'rtsgame-kmp/shared/entity/Unit.kt' (UnitType enum).
 */
data class UnitTypeDefinition(
    val id: String, // e.g., "tank", "worker", "command_center"
    val name: String, // Display name
    val modelId: String, // Reference to 3D model (from model-manifest.json)
    val baseMaxHp: Float,
    val baseSpeed: Float,
    val baseArmor: Float,
    val baseArmorType: ArmorType = ArmorType.MEDIUM,
    // Attack properties
    val baseAttackDamage: Float,
    val baseAttackRange: Float,
    val baseAttackCooldown: Float,
    val baseDamageType: DamageType = DamageType.NORMAL,
    val projectileModelId: String? = null, // For visible projectiles
    // Resource properties
    val cost: Map<ResourceType, Int> = emptyMap(),
    val providesSupply: Int = 0,
    val requiresSupply: Int = 0,
    // Abilities
    val abilities: List<String> = emptyList(), // List of ability IDs
    // Production
    val canProduce: List<String> = emptyList() // List of UnitTypeDefinition IDs it can produce
    // Add other relevant static properties: visionRange, energy, etc.
)

enum class ResourceType {
    MINERALS, // Example, could be Mass, Energy from museum
    GAS,      // Example
    SUPPLY
}

enum class DamageType {
    NORMAL, KINETIC, EXPLOSIVE, ENERGY, PIERCING, PLASMA // From museum projects
}

enum class ArmorType {
    LIGHT, MEDIUM, HEAVY, FORTIFIED, SHIELDED, BIOLOGICAL // From museum projects
}

// --- VI. Advanced Gameplay Concepts (Placeholders) ---

interface VeterancyComponent : Component {
    // Properties: experience, level, killCount, damageDealt
    // Methods: addExperience, onKill, applyBonuses
    // Origin: 'retired/unit.ts' (extensive veterancy tracking).
}

interface ShieldComponent : Component {
    // Properties: currentShieldHp, maxShieldHp, regenRate, regenDelay, damageAbsorptionRatio
    // Origin: 'retired/unit.ts' (energy shields), 'rtsgame-kmp/CombatSystem.kt'.
}

interface SpecialAbility {
    // Properties: id, name, energyCost, cooldown, range, areaOfEffect
    // Methods: canActivate(caster: EntityId, target: Target?), activate(caster: EntityId, target: Target?)
    // Origin: Grenade ability in 'retired/unit.ts', general ability list in 'rtsgame-kmp'.
}

interface ComputroniumCoreComponent : Component {
    // Properties: coreLevel, currentFocusMode (enum: OFFENSIVE, DEFENSIVE, C_C, UTILITY)
    // Methods: setFocusMode, applyModifiersToEntityStats
    // Origin: 'retired/unit.ts' (Computronium core, focus modes).
    // This is a very specific feature from the 'retired' project, might be too complex initially.
}

interface AlloySystemComponent : Component {
    // Property: alloyType: AlloyType (enum or data class)
    // Modifies base entity stats.
    // Origin: 'retired/unit.ts' (AlloyType and its modifiers).
}

// --- VII. AI Related ---
interface AIBehaviorComponent : Component {
    // Properties: currentGoal (enum: IDLE, ATTACKING, MOVING_TO_RESOURCE, BUILDING), blackboard (Map<String, Any>)
    // Methods: decideNextAction()
    // Origin: 'retired/ai/AutonomousBehavior.ts'.
}

// --- VIII. Technical Systems ---

interface DeterministicRNG {
    // Methods: nextInt(), nextFloat(), setSeed(seed: Long)
    // Origin: 'retired/core/deterministicRNG.ts'.
    // Crucial for replays and consistent simulation.
}

interface ReplaySystem {
    // Methods: startRecording(gameState: GameState), recordAction(action: Command), stopRecording(): ReplayData
    // Methods: startPlayback(replayData: ReplayData), getNextState(deltaTime: Float): GameState?
    // Origin: 'retired/core/replay/'.
}

// --- End of backlog.kt ---
