"""
Cookie Manager for handling browser cookies and session state.
"""

import json
import pickle
import os
import tempfile
import subprocess
from typing import Dict, List, Optional, Union, Tuple
from pathlib import Path
from datetime import datetime
import logging
from selenium.webdriver.remote.webdriver import WebDriver
from selenium.webdriver.remote.webelement import WebElement
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

class CookieManager:
    def __init__(self, cookie_dir: str = "cookies"):
        """
        Initialize the Cookie Manager.
        
        Args:
            cookie_dir (str): Directory to store cookie files
        """
        self.logger = logging.getLogger(__name__)
        self.cookie_dir = Path(cookie_dir)
        self.cookie_dir.mkdir(parents=True, exist_ok=True)
        
    def save_cookies(self, driver: WebDriver, domain: str) -> bool:
        """
        Save cookies from the current browser session.
        
        Args:
            driver (WebDriver): Selenium WebDriver instance
            domain (str): Domain name for the cookies
            
        Returns:
            bool: True if cookies were saved successfully
        """
        try:
            cookies = driver.get_cookies()
            if not cookies:
                self.logger.warning(f"No cookies found for domain: {domain}")
                return False
                
            # Create a timestamped filename
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            cookie_file = self.cookie_dir / f"{domain}_{timestamp}.pkl"
            
            # Save cookies using pickle
            with open(cookie_file, 'wb') as f:
                pickle.dump(cookies, f)
                
            # Also save a human-readable JSON version
            json_file = self.cookie_dir / f"{domain}_{timestamp}.json"
            with open(json_file, 'w') as f:
                json.dump(cookies, f, indent=2)
                
            # Save in aria2c format
            aria2c_file = self.cookie_dir / f"{domain}_{timestamp}.aria2c"
            self._save_aria2c_cookies(cookies, aria2c_file)
            
            # Save in curl format
            curl_file = self.cookie_dir / f"{domain}_{timestamp}.curl"
            self._save_curl_cookies(cookies, curl_file)
                
            self.logger.info(f"Saved {len(cookies)} cookies for {domain}")
            return True
            
        except Exception as e:
            self.logger.error(f"Error saving cookies: {e}")
            return False
            
    def _save_aria2c_cookies(self, cookies: List[Dict], file_path: Path):
        """
        Save cookies in aria2c format.
        
        Args:
            cookies (List[Dict]): List of cookie dictionaries
            file_path (Path): Path to save the aria2c cookie file
        """
        try:
            with open(file_path, 'w') as f:
                for cookie in cookies:
                    # aria2c format: domain\tTRUE\tpath\tSECURE\texpiry\tname\tvalue
                    secure = "TRUE" if cookie.get('secure', False) else "FALSE"
                    path = cookie.get('path', '/')
                    expiry = str(int(cookie.get('expiry', 0))) if cookie.get('expiry') else "0"
                    f.write(f"{cookie['domain']}\tTRUE\t{path}\t{secure}\t{expiry}\t{cookie['name']}\t{cookie['value']}\n")
        except Exception as e:
            self.logger.error(f"Error saving aria2c cookies: {e}")
            
    def _save_curl_cookies(self, cookies: List[Dict], file_path: Path):
        """
        Save cookies in curl format.
        
        Args:
            cookies (List[Dict]): List of cookie dictionaries
            file_path (Path): Path to save the curl cookie file
        """
        try:
            with open(file_path, 'w') as f:
                f.write("# Netscape HTTP Cookie File\n")
                f.write("# https://curl.haxx.se/rfc/cookie_spec.html\n")
                f.write("# This file was generated by selenium_console\n\n")
                
                for cookie in cookies:
                    # curl format: domain flag path secure expiry name value
                    secure = "TRUE" if cookie.get('secure', False) else "FALSE"
                    path = cookie.get('path', '/')
                    expiry = str(int(cookie.get('expiry', 0))) if cookie.get('expiry') else "0"
                    f.write(f"{cookie['domain']}\tTRUE\t{path}\t{secure}\t{expiry}\t{cookie['name']}\t{cookie['value']}\n")
        except Exception as e:
            self.logger.error(f"Error saving curl cookies: {e}")
            
    def load_cookies(self, driver: WebDriver, domain: str, use_latest: bool = True) -> bool:
        """
        Load cookies into the current browser session.
        
        Args:
            driver (WebDriver): Selenium WebDriver instance
            domain (str): Domain name for the cookies
            use_latest (bool): Whether to use the latest cookie file or prompt for selection
            
        Returns:
            bool: True if cookies were loaded successfully
        """
        try:
            cookie_files = list(self.cookie_dir.glob(f"{domain}_*.pkl"))
            if not cookie_files:
                self.logger.warning(f"No cookie files found for domain: {domain}")
                return False
                
            # Sort by modification time (newest first)
            cookie_files.sort(key=lambda x: x.stat().st_mtime, reverse=True)
            
            if use_latest:
                cookie_file = cookie_files[0]
            else:
                # TODO: Implement cookie file selection UI
                cookie_file = cookie_files[0]
                
            # Load cookies from pickle file
            with open(cookie_file, 'rb') as f:
                cookies = pickle.load(f)
                
            # Add cookies to the current session
            for cookie in cookies:
                try:
                    driver.add_cookie(cookie)
                except Exception as e:
                    self.logger.warning(f"Error adding cookie: {e}")
                    
            self.logger.info(f"Loaded {len(cookies)} cookies for {domain}")
            return True
            
        except Exception as e:
            self.logger.error(f"Error loading cookies: {e}")
            return False
            
    def get_cookie_value(self, driver: WebDriver, name: str) -> Optional[str]:
        """
        Get a specific cookie value by name.
        
        Args:
            driver (WebDriver): Selenium WebDriver instance
            name (str): Name of the cookie
            
        Returns:
            Optional[str]: Cookie value if found, None otherwise
        """
        try:
            cookie = driver.get_cookie(name)
            return cookie.get('value') if cookie else None
        except Exception as e:
            self.logger.error(f"Error getting cookie value: {e}")
            return None
            
    def delete_cookies(self, driver: WebDriver, domain: Optional[str] = None) -> bool:
        """
        Delete cookies from the current browser session.
        
        Args:
            driver (WebDriver): Selenium WebDriver instance
            domain (Optional[str]): Domain to delete cookies for, or None for all
            
        Returns:
            bool: True if cookies were deleted successfully
        """
        try:
            if domain:
                cookies = driver.get_cookies()
                for cookie in cookies:
                    if domain in cookie.get('domain', ''):
                        driver.delete_cookie(cookie['name'])
            else:
                driver.delete_all_cookies()
            return True
        except Exception as e:
            self.logger.error(f"Error deleting cookies: {e}")
            return False
            
    def export_cookies_for_quic(self, domain: str) -> Optional[Dict[str, str]]:
        """
        Export cookies in a format suitable for the QUIC client.
        
        Args:
            domain (str): Domain name for the cookies
            
        Returns:
            Optional[Dict[str, str]]: Dictionary of cookie name-value pairs
        """
        try:
            cookie_files = list(self.cookie_dir.glob(f"{domain}_*.pkl"))
            if not cookie_files:
                return None
                
            # Use the latest cookie file
            cookie_file = max(cookie_files, key=lambda x: x.stat().st_mtime)
            
            with open(cookie_file, 'rb') as f:
                cookies = pickle.load(f)
                
            # Convert to name-value pairs
            cookie_dict = {cookie['name']: cookie['value'] for cookie in cookies}
            return cookie_dict
            
        except Exception as e:
            self.logger.error(f"Error exporting cookies for QUIC: {e}")
            return None
            
    def wait_for_cookie(self, driver: WebDriver, name: str, timeout: int = 10) -> bool:
        """
        Wait for a specific cookie to be present.
        
        Args:
            driver (WebDriver): Selenium WebDriver instance
            name (str): Name of the cookie to wait for
            timeout (int): Maximum time to wait in seconds
            
        Returns:
            bool: True if cookie was found within timeout
        """
        try:
            WebDriverWait(driver, timeout).until(
                lambda d: d.get_cookie(name) is not None
            )
            return True
        except Exception:
            return False
            
    def get_aria2c_cookie_file(self, domain: str) -> Optional[Path]:
        """
        Get the latest aria2c cookie file for a domain.
        
        Args:
            domain (str): Domain name for the cookies
            
        Returns:
            Optional[Path]: Path to the latest aria2c cookie file
        """
        try:
            cookie_files = list(self.cookie_dir.glob(f"{domain}_*.aria2c"))
            if not cookie_files:
                return None
            return max(cookie_files, key=lambda x: x.stat().st_mtime)
        except Exception as e:
            self.logger.error(f"Error getting aria2c cookie file: {e}")
            return None
            
    def get_curl_cookie_file(self, domain: str) -> Optional[Path]:
        """
        Get the latest curl cookie file for a domain.
        
        Args:
            domain (str): Domain name for the cookies
            
        Returns:
            Optional[Path]: Path to the latest curl cookie file
        """
        try:
            cookie_files = list(self.cookie_dir.glob(f"{domain}_*.curl"))
            if not cookie_files:
                return None
            return max(cookie_files, key=lambda x: x.stat().st_mtime)
        except Exception as e:
            self.logger.error(f"Error getting curl cookie file: {e}")
            return None
            
    def execute_with_cookies(self, command: str, domain: str, use_aria2c: bool = True) -> Tuple[bool, str]:
        """
        Execute a command with cookies from either aria2c or curl format.
        
        Args:
            command (str): Command to execute
            domain (str): Domain name for the cookies
            use_aria2c (bool): Whether to use aria2c format (True) or curl format (False)
            
        Returns:
            Tuple[bool, str]: (success, output)
        """
        try:
            cookie_file = self.get_aria2c_cookie_file(domain) if use_aria2c else self.get_curl_cookie_file(domain)
            if not cookie_file:
                return False, f"No cookie file found for domain: {domain}"
                
            # Create a temporary script to execute the command with cookies
            with tempfile.NamedTemporaryFile(mode='w', suffix='.sh', delete=False) as f:
                if use_aria2c:
                    f.write(f"aria2c --load-cookies={cookie_file} {command}\n")
                else:
                    f.write(f"curl -b {cookie_file} {command}\n")
                script_path = f.name
                
            # Make the script executable
            os.chmod(script_path, 0o755)
            
            # Execute the script
            result = subprocess.run([script_path], capture_output=True, text=True)
            
            # Clean up
            os.unlink(script_path)
            
            return result.returncode == 0, result.stdout if result.returncode == 0 else result.stderr
            
        except Exception as e:
            self.logger.error(f"Error executing command with cookies: {e}")
            return False, str(e) 