#!/bin/bash
set -euo pipefail

# Async Museum Worker - Analyzes and integrates beneficial museum code
# Usage: KEYWORD=<keyword> WORKER_ID=<id> ./async-museum-worker.sh

KEYWORD="${KEYWORD:-unknown}"
WORKER_ID="${WORKER_ID:-$$}"
TIMESTAMP="${TIMESTAMP:-$(date +%Y%m%d_%H%M%S)}"
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BRANCH_NAME="museum-review-${KEYWORD}-${TIMESTAMP}"
WORK_DIR="tmpdir/worker-${WORKER_ID}-${KEYWORD}"
TRANSCRIPT="museum/worker-${WORKER_ID}-${KEYWORD}-${TIMESTAMP}.md"

cd "${PROJECT_ROOT}"
mkdir -p tmpdir museum

# Worker logging
wlog() {
    echo "[WORKER-${WORKER_ID}] [${KEYWORD}] [$(date '+%H:%M:%S')] $*" | tee -a "${TRANSCRIPT}"
}

# Initialize worker transcript
cat > "${TRANSCRIPT}" << EOF
# Museum Worker ${WORKER_ID}: ${KEYWORD}

Generated: $(date -Iseconds)
Branch: ${BRANCH_NAME}
Worker: ${WORKER_ID}

## Beneficial Code Analysis

EOF

wlog "=== Starting Async Museum Worker for ${KEYWORD} ==="

# Create isolated work environment
mkdir -p "${WORK_DIR}"
cd "${WORK_DIR}"

# Stash any uncommitted changes
if ! git diff --quiet; then
    wlog "Stashing uncommitted changes"
    git stash push -m "worker-${WORKER_ID}-${KEYWORD}-pre"
fi

# Create and switch to isolated branch
wlog "Creating isolated branch: ${BRANCH_NAME}"
git checkout -b "${BRANCH_NAME}" main

# Scan for museum artifacts
wlog "Scanning for museum artifacts..."
FOUND_ARTIFACTS=()

# Check museum/${KEYWORD}/
if [[ -d "${PROJECT_ROOT}/museum/${KEYWORD}" ]]; then
    wlog "Found museum/${KEYWORD}/"
    find "${PROJECT_ROOT}/museum/${KEYWORD}" -name "*.kt" -o -name "*.java" | while read -r file; do
        if [[ -f "${file}" ]]; then
            FOUND_ARTIFACTS+=("${file}")
            wlog "  - Artifact: $(basename "${file}")"
        fi
    done
fi

# Check museum/Review/trikeshed-core/ for concurrent collections
if [[ "${KEYWORD}" == "reactor" ]] && [[ -d "${PROJECT_ROOT}/museum/Review/trikeshed-core" ]]; then
    wlog "Found concurrent collections in museum/Review/trikeshed-core/"
    find "${PROJECT_ROOT}/museum/Review/trikeshed-core" -name "*.kt" | while read -r file; do
        if [[ -f "${file}" ]]; then
            FOUND_ARTIFACTS+=("${file}")
            wlog "  - Collection: $(basename "${file}")"
        fi
    done
fi

# Check museum/parse/ for parser combinators
if [[ "${KEYWORD}" == "ljson" ]] && [[ -d "${PROJECT_ROOT}/museum/parse" ]]; then
    wlog "Found parser combinators in museum/parse/"
    find "${PROJECT_ROOT}/museum/parse" -name "*.kt" | while read -r file; do
        if [[ -f "${file}" ]]; then
            FOUND_ARTIFACTS+=("${file}")
            wlog "  - Parser: $(basename "${file}")"
        fi
    done
fi

# Check museum/unstable_features/ for services
if [[ "${KEYWORD}" == "couchdb" ]] && [[ -d "${PROJECT_ROOT}/museum/unstable_features/services" ]]; then
    wlog "Found services in museum/unstable_features/"
    find "${PROJECT_ROOT}/museum/unstable_features/services" -name "*Couch*.kt" | while read -r file; do
        if [[ -f "${file}" ]]; then
            FOUND_ARTIFACTS+=("${file}")
            wlog "  - Service: $(basename "${file}")"
        fi
    done
fi

# Process artifacts if found
if [[ ${#FOUND_ARTIFACTS[@]} -gt 0 ]]; then
    wlog "Processing ${#FOUND_ARTIFACTS[@]} artifacts..."
    
    # Create integration directory
    mkdir -p "${PROJECT_ROOT}/Trikeshed/src/commonMain/kotlin/borg/trikeshed/museum/${KEYWORD}"
    
    # Process each artifact
    for artifact in "${FOUND_ARTIFACTS[@]}"; do
        if [[ -f "${artifact}" ]]; then
            basename=$(basename "${artifact}")
            target="${PROJECT_ROOT}/Trikeshed/src/commonMain/kotlin/borg/trikeshed/museum/${KEYWORD}/${basename}"
            
            wlog "Adapting artifact: ${basename}"
            
            # Copy and adapt the artifact
            cp "${artifact}" "${target}"
            
            # Adapt package declaration
            sed -i.bak "s/^package .*/package borg.trikeshed.museum.${KEYWORD}/" "${target}"
            
            # Adapt imports for current architecture
            sed -i.bak "s/import borg\.trikeshed\.lib\.Series/import borg.trikeshed.lib.Indexed/g" "${target}"
            sed -i.bak "s/MetaSeries/Indexed/g" "${target}"
            sed -i.bak "s/Series</Indexed</g" "${target}"
            
            # Remove @JvmInline if not supported in commonMain
            if grep -q "@JvmInline" "${target}"; then
                wlog "  - Removing @JvmInline for commonMain compatibility"
                sed -i.bak "s/@JvmInline//g" "${target}"
            fi
            
            # Clean up backup files
            rm -f "${target}.bak"
            
            wlog "  ✓ Adapted ${basename}"
        fi
    done
    
    # Add integration summary
    cat > "${PROJECT_ROOT}/Trikeshed/src/commonMain/kotlin/borg/trikeshed/museum/${KEYWORD}/Integration.kt" << EOF
package borg.trikeshed.museum.${KEYWORD}

/**
 * ${KEYWORD^} Museum Integration Summary
 * Generated by Worker ${WORKER_ID} at ${TIMESTAMP}
 * 
 * Beneficial artifacts integrated from museum/${KEYWORD}:
$(for artifact in "${FOUND_ARTIFACTS[@]}"; do echo " * - $(basename "${artifact}")"; done)
 */
object ${KEYWORD^}Integration {
    /**
     * Integration metadata
     */
    val metadata = mapOf(
        "worker" to "${WORKER_ID}",
        "timestamp" to "${TIMESTAMP}",
        "artifacts" to ${#FOUND_ARTIFACTS[@]},
        "keyword" to "${KEYWORD}"
    )
    
    fun summary(): String = "Integrated ${#FOUND_ARTIFACTS[@]} beneficial artifacts from museum/${KEYWORD}"
}
EOF

    wlog "Created integration summary"
    
    # Test basic compilation (simple syntax check)
    wlog "Testing integration compilation..."
    compile_errors=0
    
    for file in "${PROJECT_ROOT}/Trikeshed/src/commonMain/kotlin/borg/trikeshed/museum/${KEYWORD}"/*.kt; do
        if [[ -f "${file}" ]]; then
            # Basic syntax validation
            if ! kotlinc "${file}" -cp "${PROJECT_ROOT}/Trikeshed/build/libs/*" -no-stdlib -no-reflect >/dev/null 2>&1; then
                wlog "  ⚠ Syntax issues in $(basename "${file}") - may need manual fixes"
                ((compile_errors++))
            fi
        fi
    done
    
    if [[ ${compile_errors} -eq 0 ]]; then
        wlog "✓ All integrations pass basic syntax check"
    else
        wlog "⚠ ${compile_errors} files may need manual review"
    fi
    
    # Commit the beneficial integrations
    git add "Trikeshed/src/commonMain/kotlin/borg/trikeshed/museum/${KEYWORD}/"
    git commit -m "Integrate beneficial ${KEYWORD} artifacts from museum

Worker ${WORKER_ID} processed ${#FOUND_ARTIFACTS[@]} artifacts:
$(for artifact in "${FOUND_ARTIFACTS[@]}"; do echo "- $(basename "${artifact}")"; done)

Adaptations made:
- Updated package declarations
- Series → Indexed migration
- CommonMain compatibility fixes
- Integration summary created

🤖 Generated with [Claude Code](https://claude.ai/code)

Co-Authored-By: Claude <noreply@anthropic.com>"

    wlog "✓ Committed beneficial integrations"
    
else
    wlog "No artifacts found for ${KEYWORD} - creating placeholder"
    
    # Create minimal placeholder
    mkdir -p "${PROJECT_ROOT}/Trikeshed/src/commonMain/kotlin/borg/trikeshed/museum"
    cat > "${PROJECT_ROOT}/Trikeshed/src/commonMain/kotlin/borg/trikeshed/museum/${KEYWORD^}Placeholder.kt" << EOF
package borg.trikeshed.museum

/**
 * ${KEYWORD^} placeholder - no artifacts found in museum
 * Worker ${WORKER_ID} at ${TIMESTAMP}
 */
object ${KEYWORD^}Placeholder {
    fun status() = "No museum artifacts found for ${KEYWORD}"
}
EOF

    git add "Trikeshed/src/commonMain/kotlin/borg/trikeshed/museum/${KEYWORD^}Placeholder.kt"
    git commit -m "Add ${KEYWORD} placeholder - no museum artifacts found"
    
    wlog "✓ Created placeholder (no artifacts found)"
fi

# Return to main branch (preserving our work branch)
git checkout main

# Summary
wlog "=== Worker ${WORKER_ID} Completed for ${KEYWORD} ==="
echo "" >> "${TRANSCRIPT}"
echo "## Summary" >> "${TRANSCRIPT}"
echo "- Worker: ${WORKER_ID}" >> "${TRANSCRIPT}"
echo "- Keyword: ${KEYWORD}" >> "${TRANSCRIPT}"
echo "- Branch: ${BRANCH_NAME}" >> "${TRANSCRIPT}"
echo "- Artifacts processed: ${#FOUND_ARTIFACTS[@]}" >> "${TRANSCRIPT}"
echo "- Status: Success" >> "${TRANSCRIPT}"
echo "- Timestamp: $(date -Iseconds)" >> "${TRANSCRIPT}"

wlog "Transcript saved: ${TRANSCRIPT}"
wlog "Branch preserved: ${BRANCH_NAME}"
wlog "Worker ${WORKER_ID} completed successfully"