#!/bin/bash
set -euo pipefail

# Dummy Museum Review Script for Testing
# Tests the basic museum review workflow without complexity

TIMESTAMP=$(date +%Y%m%d_%H%M%S)
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TRANSCRIPT_FILE="museum/transcript-dummy-${TIMESTAMP}.md"
TMPDIR_BASE="tmpdir/museum-dummy-${TIMESTAMP}"

cd "${PROJECT_ROOT}"

# Ensure required directories exist
mkdir -p museum tmpdir "${TMPDIR_BASE}"

# Function to log with timestamp
log() {
    echo "[DUMMY] [$(date '+%H:%M:%S')] $*" | tee -a "${TRANSCRIPT_FILE}"
}

# Initialize transcript
cat > "${TRANSCRIPT_FILE}" << EOF
# Dummy Museum Review Test

Generated: $(date -Iseconds)

## Test Results

EOF

log "=== Starting Dummy Museum Review Test ==="

# Test 1: Branch creation
BRANCH_NAME="museum-dummy-test-${TIMESTAMP}"
log "Test 1: Creating test branch: ${BRANCH_NAME}"

# Ensure clean working tree
if ! git diff --quiet; then
    log "Working tree not clean, stashing changes"
    git stash push -m "museum-dummy-pre-${TIMESTAMP}"
fi

# Create and switch to test branch
git checkout -b "${BRANCH_NAME}" main
log "✓ Branch created successfully"

# Test 2: Create minimal integration file
log "Test 2: Creating minimal integration file"
mkdir -p "Trikeshed/src/commonMain/kotlin/borg/trikeshed/museum"

cat > "Trikeshed/src/commonMain/kotlin/borg/trikeshed/museum/DummyIntegration.kt" << 'EOF'
package borg.trikeshed.museum

/**
 * Dummy integration for testing museum review system
 */
object DummyIntegration {
    fun test(): String = "museum-dummy-test"
}
EOF

log "✓ Integration file created"

# Test 3: Compilation check
log "Test 3: Testing compilation"
cd "${PROJECT_ROOT}"

if ./gradlew compileCommonMainKotlinMetadata --console=plain --no-daemon >/dev/null 2>&1; then
    log "✓ Compilation successful"
    
    # Test 4: Commit
    log "Test 4: Committing changes"
    git add "Trikeshed/src/commonMain/kotlin/borg/trikeshed/museum/DummyIntegration.kt"
    git commit -m "Add dummy museum integration for testing

Generated by dummy museum review test.

🤖 Generated with [Claude Code](https://claude.ai/code)

Co-Authored-By: Claude <noreply@anthropic.com>"
    
    log "✓ Changes committed successfully"
else
    log "✗ Compilation failed"
    git checkout .  # Revert changes
    log "✓ Reverted breaking changes"
fi

# Test 5: Return to main branch
log "Test 5: Returning to main branch"
git checkout main
log "✓ Returned to main branch"

# Test 6: Cleanup tmpdir
log "Test 6: Cleanup test artifacts"
rm -rf "${TMPDIR_BASE}"
log "✓ Cleanup completed"

log "=== Dummy Museum Review Test Completed ==="

# Summary
echo "" >> "${TRANSCRIPT_FILE}"
echo "## Summary" >> "${TRANSCRIPT_FILE}"
echo "- Test branch: ${BRANCH_NAME}" >> "${TRANSCRIPT_FILE}"
echo "- Transcript: ${TRANSCRIPT_FILE}" >> "${TRANSCRIPT_FILE}"
echo "- Status: All tests passed" >> "${TRANSCRIPT_FILE}"
echo "- Timestamp: $(date -Iseconds)" >> "${TRANSCRIPT_FILE}"

log "Test transcript saved to: ${TRANSCRIPT_FILE}"
log "Test branch available: ${BRANCH_NAME}"
log "Dummy museum review test completed successfully"