#!/bin/bash
set -euo pipefail

# Museum Concurrent Review Controller
# Manages parallel museum keyword reviews with quota break resilience

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
TRANSCRIPT_FILE="museum/transcript-${TIMESTAMP}.md"
TMPDIR_BASE="tmpdir/museum-review-${TIMESTAMP}"
MAX_CONCURRENT=3
QUOTA_RETRY_DELAY=300  # 5 minutes

# Museum keywords to process
KEYWORDS=(
    "gztool"
    "http2" 
    "http_1_1"
    "reactor"
    "relaxfactory"
    "threads"
    "zran"
    "ccek"
    "couchdb"
    "ipfs"
    "quic"
    "ljson"
)

# State tracking
declare -a ACTIVE_PIDS
declare -a COMPLETED_KEYWORDS
declare -a FAILED_KEYWORDS
RESUME_STATE_FILE="tmpdir/museum-review-state-${TIMESTAMP}.json"

cd "${PROJECT_ROOT}"

# Ensure required directories exist
mkdir -p museum tmpdir "${TMPDIR_BASE}"

# Initialize transcript
cat > "${TRANSCRIPT_FILE}" << 'EOF'
# Museum Concurrent Review Transcript

Generated by concurrent museum review system.
Timestamp: $(date -Iseconds)

## Overview
This transcript documents the concurrent review of museum keywords for beneficial code integration.

## Keywords Processed
EOF

echo "Keywords: ${KEYWORDS[*]}" >> "${TRANSCRIPT_FILE}"
echo -e "\n## Review Results\n" >> "${TRANSCRIPT_FILE}"

# Function to log with timestamp
log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*" | tee -a "${TRANSCRIPT_FILE}"
}

# Function to save state for resumption
save_state() {
    local completed_json="[]"
    local failed_json="[]"
    local active_json="[]"
    
    if [[ ${#COMPLETED_KEYWORDS[@]} -gt 0 ]]; then
        completed_json=$(printf '%s\n' "${COMPLETED_KEYWORDS[@]}" | jq -R . | jq -s .)
    fi
    
    if [[ ${#FAILED_KEYWORDS[@]} -gt 0 ]]; then
        failed_json=$(printf '%s\n' "${FAILED_KEYWORDS[@]}" | jq -R . | jq -s .)
    fi
    
    if [[ $# -gt 0 ]]; then
        active_json=$(printf '%s\n' "${@}" | jq -R . | jq -s .)
    fi
    
    cat > "${RESUME_STATE_FILE}" << EOF
{
  "timestamp": "${TIMESTAMP}",
  "completed": ${completed_json},
  "failed": ${failed_json},
  "active_keywords": ${active_json}
}
EOF
}

# Function to handle quota breaks
handle_quota_break() {
    local keyword="$1"
    log "QUOTA BREAK detected for keyword: ${keyword}"
    log "Pausing for ${QUOTA_RETRY_DELAY} seconds before retry..."
    sleep "${QUOTA_RETRY_DELAY}"
    log "Resuming ${keyword} after quota break"
}

# Function to start keyword review
start_keyword_review() {
    local keyword="$1"
    local review_script="${SCRIPT_DIR}/museum-review-${keyword}.sh"
    
    if [[ ! -f "${review_script}" ]]; then
        log "Creating review script for keyword: ${keyword}"
        create_keyword_script "${keyword}"
    fi
    
    log "Starting review for keyword: ${keyword}"
    
    # Start in background with output redirection
    (
        export MUSEUM_KEYWORD="${keyword}"
        export MUSEUM_TIMESTAMP="${TIMESTAMP}"
        export MUSEUM_TMPDIR="${TMPDIR_BASE}/${keyword}"
        export MUSEUM_TRANSCRIPT="${TRANSCRIPT_FILE}"
        
        mkdir -p "${MUSEUM_TMPDIR}"
        
        # Run with quota break handling
        while true; do
            if bash "${review_script}" 2>&1 | tee -a "${TRANSCRIPT_FILE}"; then
                break
            else
                local exit_code=$?
                if [[ ${exit_code} -eq 42 ]]; then  # Special quota break exit code
                    handle_quota_break "${keyword}"
                else
                    log "ERROR: Keyword ${keyword} failed with exit code ${exit_code}"
                    break
                fi
            fi
        done
    ) &
    
    local pid=$!
    ACTIVE_PIDS+=("${pid}")
    log "Started ${keyword} review with PID: ${pid}"
    
    return 0
}

# Function to wait for available slot
wait_for_slot() {
    while [[ ${#ACTIVE_PIDS[@]} -ge ${MAX_CONCURRENT} ]]; do
        sleep 1
        
        # Check for completed processes
        local new_pids=()
        for pid in "${ACTIVE_PIDS[@]}"; do
            if kill -0 "${pid}" 2>/dev/null; then
                new_pids+=("${pid}")
            else
                wait "${pid}"
                local exit_code=$?
                log "Process ${pid} completed with exit code: ${exit_code}"
            fi
        done
        ACTIVE_PIDS=("${new_pids[@]}")
    done
}

# Function to create keyword-specific review script
create_keyword_script() {
    local keyword="$1"
    local script_path="${SCRIPT_DIR}/museum-review-${keyword}.sh"
    
    cat > "${script_path}" << 'EOF'
#!/bin/bash
set -euo pipefail

# Museum Review Script for Keyword: ${MUSEUM_KEYWORD}
# Generated by museum-concurrent-review.sh

KEYWORD="${MUSEUM_KEYWORD}"
TIMESTAMP="${MUSEUM_TIMESTAMP}"
TMPDIR="${MUSEUM_TMPDIR}"
TRANSCRIPT="${MUSEUM_TRANSCRIPT}"
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

cd "${PROJECT_ROOT}"

# Function to log with keyword prefix
klog() {
    echo "[${KEYWORD}] [$(date '+%H:%M:%S')] $*" | tee -a "${TRANSCRIPT}"
}

# Function to handle quota breaks
quota_break() {
    klog "QUOTA_BREAK: Exiting with code 42 for retry"
    exit 42
}

# Create isolated branch
BRANCH_NAME="museum-review-${KEYWORD}-${TIMESTAMP}"
klog "Creating isolated branch: ${BRANCH_NAME}"

# Ensure clean working tree
if ! git diff --quiet; then
    klog "Working tree not clean, stashing changes"
    git stash push -m "museum-review-${KEYWORD}-pre-${TIMESTAMP}"
fi

# Create and switch to isolated branch
git checkout -b "${BRANCH_NAME}" main

# Set up isolated tmpdir
mkdir -p "${TMPDIR}"
cd "${TMPDIR}"

klog "=== Starting Museum Review for ${KEYWORD} ==="

# Look for museum keyword in various locations
FOUND_CONTENT=false

# Check museum/flat/${KEYWORD}
if [[ -d "${PROJECT_ROOT}/museum/flat/${KEYWORD}" ]]; then
    klog "Found museum/flat/${KEYWORD}"
    FOUND_CONTENT=true
    
    # Review content in museum/flat
    find "${PROJECT_ROOT}/museum/flat/${KEYWORD}" -name "*.kt" -o -name "*.java" -o -name "*.py" | while read -r file; do
        klog "Reviewing: ${file}"
        
        # Extract beneficial patterns (basic analysis)
        if grep -q "class\|interface\|fun\|data class" "${file}" 2>/dev/null; then
            klog "  -> Contains class/function definitions"
            
            # Copy to tmpdir for analysis
            cp "${file}" "${TMPDIR}/"
            
            # Basic adaptation analysis
            if grep -q "System\." "${file}" 2>/dev/null; then
                klog "  -> Needs System.* adaptation"
            fi
            
            if grep -q "runBlocking" "${file}" 2>/dev/null; then
                klog "  -> Needs runBlocking adaptation"
            fi
            
            if grep -q "Series\|MetaSeries" "${file}" 2>/dev/null; then
                klog "  -> Needs Series→Indexed migration"
            fi
        fi
    done
fi

# Check museum/${KEYWORD}
if [[ -d "${PROJECT_ROOT}/museum/${KEYWORD}" ]]; then
    klog "Found museum/${KEYWORD}"
    FOUND_CONTENT=true
fi

# Check for keyword in existing TrikeShed code
EXISTING_REFS=$(grep -r "${KEYWORD}" "${PROJECT_ROOT}/Trikeshed/src" --include="*.kt" | wc -l || echo "0")
if [[ ${EXISTING_REFS} -gt 0 ]]; then
    klog "Found ${EXISTING_REFS} existing references to ${KEYWORD} in TrikeShed"
    FOUND_CONTENT=true
fi

if [[ "${FOUND_CONTENT}" == "false" ]]; then
    klog "No museum content found for keyword: ${KEYWORD}"
    klog "Creating placeholder integration point"
    
    # Create basic integration point for future use
    mkdir -p "${PROJECT_ROOT}/Trikeshed/src/commonMain/kotlin/borg/trikeshed/museum"
    cat > "${PROJECT_ROOT}/Trikeshed/src/commonMain/kotlin/borg/trikeshed/museum/${KEYWORD^}Integration.kt" << INTEGRATION_EOF
package borg.trikeshed.museum

/**
 * Integration point for ${KEYWORD} museum artifacts
 * Generated by museum review system
 * 
 * This serves as a placeholder for future beneficial code integration
 * from museum/${KEYWORD} when artifacts become available.
 */
object ${KEYWORD^}Integration {
    /**
     * Placeholder for ${KEYWORD} integration
     * TODO: Review and integrate beneficial patterns from museum/${KEYWORD}
     */
    fun placeholder() {
        // Future integration point
    }
}
INTEGRATION_EOF
    
    # Test compilation
    cd "${PROJECT_ROOT}"
    if ! ./gradlew compileCommonMainKotlinMetadata --console=plain --no-daemon >/dev/null 2>&1; then
        klog "ERROR: Integration placeholder breaks compilation"
        git checkout .  # Revert changes
        klog "Reverted breaking changes"
    else
        klog "Integration placeholder compiles successfully"
        git add "Trikeshed/src/commonMain/kotlin/borg/trikeshed/museum/${KEYWORD^}Integration.kt"
        git commit -m "Add ${KEYWORD} museum integration placeholder

Generated museum integration point for future beneficial code.

🤖 Generated with [Claude Code](https://claude.ai/code)

Co-Authored-By: Claude <noreply@anthropic.com>"
        
        klog "Committed integration placeholder"
    fi
else
    klog "Found museum content - detailed analysis would be implemented here"
    klog "For now, creating minimal integration point"
fi

klog "=== Completed Museum Review for ${KEYWORD} ==="

# Return to main branch
git checkout main

klog "Museum review for ${KEYWORD} completed successfully"
EOF

    chmod +x "${script_path}"
    
    # Replace template variables in the script
    sed -i.bak "s/\${MUSEUM_KEYWORD}/${keyword}/g" "${script_path}"
    rm "${script_path}.bak"
}

# Main execution
log "Starting concurrent museum review system"
log "Max concurrent processes: ${MAX_CONCURRENT}"
log "Keywords to process: ${KEYWORDS[*]}"

# Process keywords with concurrency control
for keyword in "${KEYWORDS[@]}"; do
    wait_for_slot
    start_keyword_review "${keyword}"
    save_state "${KEYWORDS[@]}"
    
    # Small delay to prevent overwhelming
    sleep 2
done

# Wait for all remaining processes
log "Waiting for all keyword reviews to complete..."
for pid in "${ACTIVE_PIDS[@]}"; do
    wait "${pid}"
    local exit_code=$?
    log "Process ${pid} final exit code: ${exit_code}"
done

# Final summary
log "=== Museum Review Summary ==="
log "Completed keywords: ${#COMPLETED_KEYWORDS[@]}"
log "Failed keywords: ${#FAILED_KEYWORDS[@]}"

# List created branches
log "Created branches:"
git branch | grep "museum-review-.*-${TIMESTAMP}" | while read -r branch; do
    log "  - ${branch}"
done

log "Transcript saved to: ${TRANSCRIPT_FILE}"
log "Museum concurrent review completed"

echo -e "\n## Final Summary\n" >> "${TRANSCRIPT_FILE}"
echo "- Total keywords processed: ${#KEYWORDS[@]}" >> "${TRANSCRIPT_FILE}"
echo "- Successful reviews: ${#COMPLETED_KEYWORDS[@]}" >> "${TRANSCRIPT_FILE}"
echo "- Failed reviews: ${#FAILED_KEYWORDS[@]}" >> "${TRANSCRIPT_FILE}"
echo "- Timestamp: $(date -Iseconds)" >> "${TRANSCRIPT_FILE}"