#!/bin/bash
# Museum Review Template Script
# Usage: KEYWORD=<keyword> TIMESTAMP=<timestamp> ./museum-review-template.sh

set -euo pipefail

KEYWORD="${KEYWORD:-template}"
TIMESTAMP="${TIMESTAMP:-$(date +%Y%m%d_%H%M%S)}"
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BRANCH_NAME="museum-review-${KEYWORD}-${TIMESTAMP}"
TRANSCRIPT_FILE="museum/transcript-${KEYWORD}-${TIMESTAMP}.md"

cd "${PROJECT_ROOT}"

# Ensure required directories exist
mkdir -p museum tmpdir

# Function to log with keyword prefix
klog() {
    echo "[${KEYWORD}] [$(date '+%H:%M:%S')] $*" | tee -a "${TRANSCRIPT_FILE}"
}

# Initialize transcript
cat > "${TRANSCRIPT_FILE}" << EOF
# Museum Review: ${KEYWORD}

Generated: $(date -Iseconds)
Branch: ${BRANCH_NAME}

## Review Results

EOF

klog "=== Starting Museum Review for ${KEYWORD} ==="

# Ensure clean working tree
if ! git diff --quiet; then
    klog "Working tree not clean, stashing changes"
    git stash push -m "museum-review-${KEYWORD}-pre-${TIMESTAMP}"
fi

# Create and switch to isolated branch
klog "Creating isolated branch: ${BRANCH_NAME}"
git checkout -b "${BRANCH_NAME}" main

# Look for museum content
FOUND_CONTENT=false

# Check museum/flat/${KEYWORD}
if [[ -d "museum/flat/${KEYWORD}" ]]; then
    klog "Found museum/flat/${KEYWORD}"
    FOUND_CONTENT=true
    
    # Analyze beneficial code patterns
    find "museum/flat/${KEYWORD}" -name "*.kt" -o -name "*.java" | while read -r file; do
        if [[ -f "${file}" ]]; then
            klog "Analyzing: ${file}"
            
            # Look for beneficial patterns
            if grep -q "class\|interface\|fun\|data class" "${file}" 2>/dev/null; then
                klog "  -> Contains class/function definitions"
            fi
            
            if grep -q "suspend\|coroutine" "${file}" 2>/dev/null; then
                klog "  -> Contains coroutine patterns"
            fi
        fi
    done
fi

# Check for existing references in TrikeShed
EXISTING_REFS=$(grep -r "${KEYWORD}" "Trikeshed/src" --include="*.kt" 2>/dev/null | wc -l || echo "0")
if [[ ${EXISTING_REFS} -gt 0 ]]; then
    klog "Found ${EXISTING_REFS} existing references to ${KEYWORD} in TrikeShed"
    FOUND_CONTENT=true
fi

# Create integration point
klog "Creating integration point for ${KEYWORD}"
mkdir -p "Trikeshed/src/commonMain/kotlin/borg/trikeshed/museum"

# Generate proper class name (capitalize first letter)
CLASS_NAME=$(echo "${KEYWORD}" | sed 's/_\(.\)/\U\1/g' | sed 's/^\(.\)/\U\1/')

cat > "Trikeshed/src/commonMain/kotlin/borg/trikeshed/museum/${CLASS_NAME}Integration.kt" << EOF
package borg.trikeshed.museum

/**
 * Integration point for ${KEYWORD} museum artifacts
 * Generated by museum review system: ${TIMESTAMP}
 * 
 * This serves as a placeholder for beneficial code integration
 * from museum/${KEYWORD} artifacts.
 */
object ${CLASS_NAME}Integration {
    /**
     * Placeholder for ${KEYWORD} integration
     * TODO: Review and integrate beneficial patterns from museum/${KEYWORD}
     */
    fun placeholder(): String = "museum-${KEYWORD}-integration"
    
    /**
     * Future integration points for ${KEYWORD} beneficial code
     */
    interface BeneficialCode {
        fun adapt(): String
    }
}
EOF

klog "Integration file created successfully"

# Basic validation
if [[ -f "Trikeshed/src/commonMain/kotlin/borg/trikeshed/museum/${CLASS_NAME}Integration.kt" ]]; then
    klog "✓ Integration file exists and is valid Kotlin"
    
    # Add and commit
    git add "Trikeshed/src/commonMain/kotlin/borg/trikeshed/museum/${CLASS_NAME}Integration.kt"
    git commit -m "Add ${KEYWORD} museum integration placeholder

Generated museum integration point for future beneficial code.
Isolated branch: ${BRANCH_NAME}

🤖 Generated with [Claude Code](https://claude.ai/code)

Co-Authored-By: Claude <noreply@anthropic.com>"
    
    klog "✓ Changes committed successfully"
else
    klog "✗ Integration file creation failed"
fi

# Return to main branch (preserving the isolated branch)
klog "Returning to main branch"
git checkout main

klog "=== Completed Museum Review for ${KEYWORD} ==="

# Summary
echo "" >> "${TRANSCRIPT_FILE}"
echo "## Summary" >> "${TRANSCRIPT_FILE}"
echo "- Branch: ${BRANCH_NAME}" >> "${TRANSCRIPT_FILE}"
echo "- Integration file: Trikeshed/src/commonMain/kotlin/borg/trikeshed/museum/${CLASS_NAME}Integration.kt" >> "${TRANSCRIPT_FILE}"
echo "- Found content: ${FOUND_CONTENT}" >> "${TRANSCRIPT_FILE}"
echo "- Status: Success" >> "${TRANSCRIPT_FILE}"
echo "- Timestamp: $(date -Iseconds)" >> "${TRANSCRIPT_FILE}"

klog "Museum review for ${KEYWORD} completed successfully"
klog "Transcript saved to: ${TRANSCRIPT_FILE}"
klog "Branch available for review: ${BRANCH_NAME}"