/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/9.0.0-rc-1/samples
 */

socksplugins {
    kotlin("multiplatform") version "2.1.21"
}

group = "test"

kotlin {
    jvm()
}
