package borg.trikeshed.ksp

import com.google.devtools.ksp.processing.*
import com.google.devtools.ksp.symbol.*
import com.google.devtools.ksp.validate

/**
 * KSP Processor that generates type-safe DSL builders for classes annotated with @GenerateDsl.
 *
 * This processor creates fluent configuration APIs that follow the "ffmpeg-like" pattern:
 * - Every property becomes a chainable method
 * - Complex types get nested builder blocks
 * - Collections get specialized add/remove methods
 * - Validation is built-in where appropriate
 */
class TrikeShedDslProcessor(
    private val codeGenerator: CodeGenerator,
    private val logger: KSPLogger,
    private val options: Map<String, String>,
) : SymbolProcessor {
    override fun process(resolver: Resolver): List<KSAnnotated> {
        logger.warn("TrikeShedDslProcessor: Starting processing")
        
        val symbols = resolver.getSymbolsWithAnnotation("borg.trikeshed.ksp.GenerateDsl")
        val symbolsList = symbols.toList()
        logger.warn("TrikeShedDslProcessor: Found ${symbolsList.size} symbols with @GenerateDsl annotation")
        
        symbolsList.forEach { symbol ->
            val name = when (symbol) {
                is KSClassDeclaration -> symbol.simpleName.asString()
                is KSFunctionDeclaration -> symbol.simpleName.asString()
                is KSPropertyDeclaration -> symbol.simpleName.asString()
                else -> "Unknown symbol type"
            }
            logger.warn("TrikeShedDslProcessor: Found symbol: $name")
        }
        
        val unableToProcess = symbols.filterNot { it.validate() }.toList()

        symbols
            .filter { it is KSClassDeclaration && it.validate() }
            .forEach { classDecl ->
                val className = (classDecl as KSClassDeclaration).simpleName.asString()
                logger.warn("TrikeShedDslProcessor: Processing class: $className")
                generateDslBuilder(classDecl as KSClassDeclaration)
            }

        return unableToProcess
    }

    private fun generateDslBuilder(classDecl: KSClassDeclaration) {
        val packageName = classDecl.packageName.asString()
        val className = classDecl.simpleName.asString()
        val builderName = "${className}DslBuilder"

        val file =
            codeGenerator.createNewFile(
                dependencies = Dependencies(false, classDecl.containingFile!!),
                packageName = packageName,
                fileName = builderName,
            )

        file.use { outputStream ->
            outputStream.write(generateDslCode(packageName, className, builderName, classDecl))
        }
    }

    private fun generateDslCode(
        packageName: String,
        className: String,
        builderName: String,
        classDecl: KSClassDeclaration,
    ): ByteArray {
        val properties = classDecl.getAllProperties()
        val imports = mutableSetOf<String>()

        // Collect necessary imports
        properties.forEach { prop ->
            prop.type.resolve().declaration.qualifiedName?.asString()?.let {
                if (it.startsWith("kotlin.collections.") ||
                    it.startsWith("kotlinx.") ||
                    (!it.startsWith("kotlin.") && it.contains("."))
                ) {
                    imports.add(it)
                }
            }
        }

        val code =
            buildString {
                appendLine("package $packageName")
                appendLine()

                // Imports
                if (imports.isNotEmpty()) {
                    imports.sorted().forEach { import ->
                        appendLine("import $import")
                    }
                    appendLine()
                }

                // Builder class
                appendLine("/**")
                appendLine(" * DSL builder for [$className].")
                appendLine(" * Generated by TrikeShedDslProcessor.")
                appendLine(" */")
                appendLine("class $builderName {")

                // Properties to hold values
                properties.forEach { prop ->
                    val propName = prop.simpleName.asString()
                    val propType = prop.type.resolve()
                    val typeStr = propType.toKotlinString()

                    when {
                        propType.isMarkedNullable -> {
                            appendLine("    private var _$propName: $typeStr = null")
                        }
                        isCollection(propType) -> {
                            val elementType =
                                propType.arguments
                                    .firstOrNull()
                                    ?.type
                                    ?.resolve()
                                    ?.toKotlinString() ?: "Any"
                            appendLine("    private val _$propName = mutable${collectionType(propType)}Of<$elementType>()")
                        }
                        else -> {
                            appendLine("    private lateinit var _$propName: $typeStr")
                        }
                    }
                }

                appendLine()

                // Builder methods
                properties.forEach { prop ->
                    val propName = prop.simpleName.asString()
                    val propType = prop.type.resolve()

                    when {
                        isCollection(propType) -> {
                            generateCollectionMethods(propName, propType)
                        }
                        isComplexType(propType) -> {
                            generateNestedBuilderMethod(propName, propType)
                        }
                        else -> {
                            generateSimplePropertyMethod(propName, propType)
                        }
                    }
                    appendLine()
                }

                // Build method
                appendLine("    /**")
                appendLine("     * Builds the [$className] instance.")
                appendLine("     * @throws IllegalStateException if required properties are not set")
                appendLine("     */")
                appendLine("    fun build(): $className {")

                // Validation for required properties
                properties.filter { !it.type.resolve().isMarkedNullable && !isCollection(it.type.resolve()) }.forEach { prop ->
                    val propName = prop.simpleName.asString()
                    appendLine("        if (!::_$propName.isInitialized) {")
                    appendLine("            throw IllegalStateException(\"Property '$propName' must be set\")")
                    appendLine("        }")
                }

                // Create instance
                appendLine("        return $className(")
                properties.forEachIndexed { index, prop ->
                    val propName = prop.simpleName.asString()
                    val isLast = index == properties.toList().size - 1
                    val comma = if (isLast) "" else ","

                    if (isCollection(prop.type.resolve())) {
                        appendLine("            $propName = _$propName.toList()$comma")
                    } else {
                        appendLine("            $propName = _$propName$comma")
                    }
                }
                appendLine("        )")
                appendLine("    }")

                appendLine("}")
                appendLine()

                // Top-level DSL function
                appendLine("/**")
                appendLine(" * Creates a new [$className] using the DSL builder.")
                appendLine(" */")
                appendLine("inline fun ${className.replaceFirstChar { it.lowercase() }}(block: $builderName.() -> Unit): $className {")
                appendLine("    return $builderName().apply(block).build()")
                appendLine("}")
            }

        return code.toByteArray()
    }

    private fun StringBuilder.generateSimplePropertyMethod(
        propName: String,
        propType: KSType,
    ) {
        val typeStr = propType.toKotlinString()

        appendLine("    /**")
        appendLine("     * Sets the $propName property.")
        if (propName == "port" && typeStr == "Int") {
            appendLine("     * @param value Port number (1-65535)")
            appendLine("     * @throws IllegalArgumentException if port is out of range")
        }
        appendLine("     */")
        appendLine("    fun $propName(value: $typeStr): $builderName {")

        // Add validation for specific property types
        when {
            propName == "port" && typeStr == "Int" -> {
                appendLine("        require(value in 1..65535) { \"Port must be between 1 and 65535\" }")
            }
            propName.contains("timeout", ignoreCase = true) && typeStr == "Long" -> {
                appendLine("        require(value >= 0) { \"Timeout must be non-negative\" }")
            }
        }

        appendLine("        this._$propName = value")
        appendLine("        return this")
        appendLine("    }")
    }

    private fun StringBuilder.generateCollectionMethods(
        propName: String,
        propType: KSType,
    ) {
        val elementType =
            propType.arguments
                .firstOrNull()
                ?.type
                ?.resolve()
                ?.toKotlinString() ?: "Any"
        val singularName = propName.removeSuffix("s").removeSuffix("es")

        appendLine("    /**")
        appendLine("     * Adds a single $singularName to the collection.")
        appendLine("     */")
        appendLine("    fun $singularName(value: $elementType): $builderName {")
        appendLine("        this._$propName.add(value)")
        appendLine("        return this")
        appendLine("    }")
        appendLine()
        appendLine("    /**")
        appendLine("     * Adds multiple $propName to the collection.")
        appendLine("     */")
        appendLine("    fun $propName(vararg values: $elementType): $builderName {")
        appendLine("        this._$propName.addAll(values)")
        appendLine("        return this")
        appendLine("    }")
    }

    private fun StringBuilder.generateNestedBuilderMethod(
        propName: String,
        propType: KSType,
    ) {
        val typeStr = propType.toKotlinString()
        val nestedBuilderName = "${propType.declaration.simpleName.asString()}DslBuilder"

        appendLine("    /**")
        appendLine("     * Configures the $propName using a nested builder.")
        appendLine("     */")
        appendLine("    fun $propName(block: $nestedBuilderName.() -> Unit): $builderName {")
        appendLine("        this._$propName = $nestedBuilderName().apply(block).build()")
        appendLine("        return this")
        appendLine("    }")
    }

    private fun isCollection(type: KSType): Boolean {
        val typeName = type.declaration.qualifiedName?.asString() ?: ""
        return typeName in
            setOf(
                "kotlin.collections.List",
                "kotlin.collections.Set",
                "kotlin.collections.MutableList",
                "kotlin.collections.MutableSet",
                "kotlin.Array",
            )
    }

    private fun collectionType(type: KSType): String =
        when (type.declaration.qualifiedName?.asString()) {
            "kotlin.collections.Set", "kotlin.collections.MutableSet" -> "Set"
            else -> "List"
        }

    private fun isComplexType(type: KSType): Boolean {
        val declaration = type.declaration
        return declaration is KSClassDeclaration &&
            declaration.classKind == ClassKind.CLASS &&
            !type.declaration.packageName
                .asString()
                .startsWith("kotlin")
    }

    private fun KSType.toKotlinString(): String {
        val base = declaration.simpleName.asString()
        val typeArgs =
            if (arguments.isNotEmpty()) {
                "<${arguments.joinToString(", ") { it.type?.resolve()?.toKotlinString() ?: "*" }}>"
            } else {
                ""
            }
        val nullable = if (isMarkedNullable) "?" else ""
        return "$base$typeArgs$nullable"
    }

    companion object {
        private var builderName: String = ""
    }
}

/**
 * Provider for the TrikeShedDslProcessor
 */
class TrikeShedDslProcessorProvider : SymbolProcessorProvider {
    override fun create(environment: SymbolProcessorEnvironment): SymbolProcessor =
        TrikeShedDslProcessor(
            codeGenerator = environment.codeGenerator,
            logger = environment.logger,
            options = environment.options,
        )
}
