package moneyfan.models

/**
 * Represents a trading signal that can be generated by a trading strategy.
 */
enum class TradingSignal {
    /**
     * Signal to enter a long position or buy an asset.
     */
    BUY,

    /**
     * Signal to exit a long position or sell an asset.
     */
    SELL,

    /**
     * Signal to take no action, or maintain the current position.
     */
    HOLD
}
