package moneyfan.model

import com.ta4k.core.model.TradingPair
import java.math.BigDecimal
import java.time.Instant

/**
 * Represents a trading signal generated by a strategy
 */
sealed class TradeSignal {
    object Buy : TradeSignal()
    object Sell : TradeSignal()
    object Short : TradeSignal()
    object Cover : TradeSignal()
    object Hold : TradeSignal()
}

/**
 * Represents the result of a completed trade
 */
data class TradeResult(
    val pair: TradingPair,
    val entryPrice: BigDecimal,
    val exitPrice: BigDecimal,
    val quantity: BigDecimal,
    val pnl: BigDecimal,
    val entryTime: Instant,
    val exitTime: Instant
) 